### PR TITLE
Adding JavaScript wait examples

### PR DESCRIPTION
**Pull request by sachhu**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

1. Added tests example for javascript waits
2. Added examples  for javascript waits in the documentation

### Motivation and Context
There are no examples of javascript waits in the documentation

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

#1450

### CODE REVIEW

**Review by harsha509 — APPROVED** [review]
Thank you @sachhu !

**Comment by sachhu** [comment]
In my opinion, these failed checks are not related to my commits.

Please let me know if something needs to be done from my end.

**Review by harsha509 — APPROVED** [review]
Thank you @sachhu !

**Comment by harsha509** [comment]
Congratulations on your first contribution to Selenium Docs @sachhu  🎉 🎉 🎉 !

**Pull request merged**
