### PR TITLE
Added Chrome devtools features

### PR DESCRIPTION
**Pull request by nainappa**
### Description
Added chrome devtools features that are part of Selenium4-alpha versions. 

### Motivation and Context
The example code snippets would help the users to understand more about the features. 

### Types of changes

- [x] Change to the site (I am attaching a screenshot showing the before and after)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

After:
--------------------------------------------------------------------------------------------------------------
image

### CODE REVIEW

**Comment by nainappa** [comment]
Hi @Harsha509 

Thanks for reviewing the changes. Below are in-line response.
1. I just tried the code with Aplha-5. It is working fine. I obviously removed some unwanted code and added only important packages as those packages are new to the users. Please try the below code. This is working for me.
 `import java.util.HashMap;
import java.util.Map;

import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

public class SampleTest {
  @Test
  public void geoLocationTest() {
    // driver exe setup
    ChromeDriver driver = new ChromeDriver();
    driver.get("https://the-internet.herokuapp.com/geolocation");
    // click on WhereAmI button. That will show current coordinates
    Map coordinates = new HashMap() {
      {
        put("latitude", 50.2334);
        put("longitude", 0.2334);
        put("accuracy", 1);
      }
    };
    driver.executeCdpCommand("Emulation.setGeolocationOverride", coordinates);
    driver.navigate().refresh();
    // Now again click on WhereAmI button. That will show the changed coordinates
  }
}`
2. Network emulate feature was tested in Alpha-2. Looks like Alpha-5 has some issues. I can remove that feature for now.
3. executeCDP is part of chromium driver and Devtools is under openq.selenium. Even I was debating about adding it in "Driver idiosyncrasies" or "Webdriver". Since all these features comes under Devtools, I added as part of Webdriver. Please let me know your thoughts.

**Comment by nainappa** [comment]
Hi @Harsha509 

I removed network emulation feature. Please take a look when you have time.

**Comment by nainappa** [comment]
Hi @Harsha509 

Do you have any updates on this? If it doesnt make sense, I can close the PR.

**Comment by Harsha509** [comment]
> Hi @Harsha509
> 
> Do you have any updates on this? If it doesnt make sense, I can close the PR.

Hi @nainappa 

The PR is Awesome. Please give us some time as the the team members/core committers also have few suggestions as this is the important feature landing in Selenium4.

Regards,
Harsha.

**Comment by Harsha509** [comment]
Hi @nainappa ,


I would like to move this document to `support package` section (temporarily). Please let me know your thoughts on this.

If you are ok with it, can you please make changes. I will merge it.

Regards,
Harsha.

**Comment by nainappa** [comment]
Hi @Harsha509 Sure. I will raise PR with the changes. Thanks for the review.

**Comment by nainappa** [comment]
Hi @Harsha509,

I changed the location to Support Packages now. Please take a look when you have time.

**Comment by Harsha509** [comment]
> Hi @Harsha509,
> 
> I changed the location to Support Packages now. Please take a look when you have time.

Sure. The build is already in progress :)

I'll merge it when the build is good!

**Pull request merged**
