### PR TITLE
Fix/issue 1059

### LINKED ISSUE #1059: [🚀 Feature]: Update docs to reflect removal of `find_element_by` for `4.3`
### Feature and motivation

Just a reminder for myself to update documentation around finding elements to explain the changes and `by_` methods are no longer available.

### Usage example

.

### PR DESCRIPTION
**Pull request by jags14385**
Fixes #1059 

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by jags14385** [comment]
Used this for reference : https://stackoverflow.com/questions/69875125/find-element-by-commands-are-deprecated-in-selenium

**Comment by jags14385** [comment]
@diemol & @symonk  how should I update the info on https://www.selenium.dev/documentation/webdriver/getting_started/upgrade_to_selenium_4/#python ??

**Review by harsha509 — APPROVED** [review]
Thank you @jags14385 !

**Review by mohammad-equityzen — APPROVED** [review]

**Comment by jags14385** [comment]
I am not authorized to merge this PR. So, someone will have to do merge it for me

**Pull request merged**
