### PR TITLE
Update types_of_testing.en.md

### PR DESCRIPTION
**Pull request by tmfink10**
"what's" can stand for "what is" but not for "what it's"

Removed periods from lines that already end in punctuation.

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [x] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @tmfink10 ,

Thanks for the PR.

Can you please make similar changes to other translated pages which are in English (line zh-cn, es etc)

Thanks

**Comment by harsha509** [comment]
Hi @tmfink10 ,

Did you got a chance to look into above comments ?

Thanks,
Harsha

**Comment by tmfink10** [comment]
Hey there. Most of the translations are actually really good! I haven't
found anything else.

Trevor

**Review by harsha509 — APPROVED** [review]
Thank you @tmfink10 !

**Pull request merged**
