### PR TITLE
doc: Correct instructions to alter .profile $PATH

### PR DESCRIPTION
**Pull request by SteveParson**
### Description
Currently, instructions are provided with the intent to add the driver path to the PATH environment variable. As written, the instructions do nothing. The commands were modified make the intended changes.

### Motivation and Context
Users that aren't familiar with the PATH environment variable may get confused when the changes weren't persisted as intended.

### Types of changes

- [x] Change to the site (I have NOT double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by titusfortner — CHANGES_REQUESTED** [review]
Ah, yes, current instructions are correct for bash not zsh, which is the "new" default for mac. Probably need to make that distinction clear somehow here.

**Comment by SteveParson** [comment]
> Ah, yes, current instructions are correct for bash not zsh, which is the "new" default for mac. Probably need to make that distinction clear somehow here.

Thanks for your reply! I tested my changes in a bash shell, not zsh. I have not used zsh, but I don't think the existing instructions would be correct for that either.

**Comment by titusfortner** [comment]
Oh, I read it backwards. Echo is for bash, export is for zsh.

**Comment by SteveParson** [comment]
The problem with the existing code is that it adds to the local path, but it doesn't add anything to `.profile` as intended.

For example:
```shell
export PATH=$PATH:/opt/WebDriver/bin >> ~/.profile
```

The first part of this command redefines the PATH variable for this specific session. In other words, if the path is currently `/bin:/usr/bin`, this command will replace it with `/bin:/usr/bin:/opt/WebDriver/bin`. **This will not persist into the next shell session**

The next part of this command is intended to deal with persistence of the path. 
Note the redirect `>>`. This causes the output of the previous command to be appended to `~/.profile` as specified. 
Usually the intent of appending to `~/.profile` is to add a line to it. In that case, using `echo` (as in my PR) will print the line to stdout, which will be appended to `~/.profile` by means of  ` >> ~/.profile`
Unfortunately, there is no output from the `export` command, and thus nothing will be appended to `~/.profile`.

Now, to make things more complicated, there are multiple places to add to the user's PATH variable. For instance, on my local install of Ubuntu 18.04, adding to `~/.profile` is the best place to add it by default. However, if the user has `~/.bash_profile` or `~/.bash_login` defined, then those places will be used instead. `~/.bashrc` is also another place that these kind of things can be added.

It is my understanding that in MacOS running zsh, then `~/.zshenv` or `~/.zshrc` are the default places to add to the path, however I have not personally verified this.

**Comment by titusfortner** [comment]
This is what I'm proposing to address this... Separate Bash & Zsh tabs, and I verified these work.

(This code is buried inside #920)

https://github.com/SeleniumHQ/seleniumhq.github.io/blob/e84b02fdec51ac286c4d7666a1902cf2d34b9918/website_and_docs/content/documentation/webdriver/getting_started/install_drivers.en.md?plain=1#L171-L219

**Comment by SteveParson** [comment]
Even better!

**Pull request closed without merging**
