### PR TITLE
Create InvalidSelectorException_is_changing.md

### PR DESCRIPTION
**Pull request by MohabMohie**
documenting the change made by this PR https://github.com/SeleniumHQ/selenium/pull/11727 and its potential backwards compatibility impact

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by MohabMohie** [comment]
@diemol for your review please, the blog post for the change to invalid locator exception.

**Comment by diemol** [comment]
Now that we released 4.9.0, let's merge this.

**Comment by MohabMohie** [comment]
@diemol I don't have permission to squash/merge the PR. But I updated the branch.

**Comment by diemol** [comment]
No worries, I will merge and do some changes before publishing. Thank you.

**Review by diemol — APPROVED** [review]

**Pull request merged**
