### PR TITLE
Update _index.html

### PR DESCRIPTION
**Pull request by asolntsev**
Add Selenide maintainer name

### Types of changes
- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by titusfortner** [comment]
Yes, thanks for the fix.

**Comment by titusfortner** [comment]
Oh, I didn't add the [deploy site] to the merge 🤦 It'll get updated next time someone else does it the right way. Sorry.

**Comment by asolntsev** [comment]
Shouldn't we simplify this process?
I think site changes should be deployed automatically on every commit. It's quite cheap and fast operation, right?

**Comment by titusfortner** [comment]
Not every commit needs a deploy, though. Not sure why it was set up this way, though. Site was deployed when I added the minutes from the last meeting.

**Pull request merged**
