### PR TITLE
[java] BiDi code examples

### PR DESCRIPTION
**Pull request by sangcnguyen**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by titusfortner** [comment]
Thank you for doing this. This looks great!
Also, I've been completely reworking all of this for about a week now, so we definitely have some duplicated effort. 😂 

I just kicked off the preview build. We can merge if the line numbers match up properly, and I'll rebase what I have off of it.

**Comment by sangcnguyen** [comment]
Thank you for keeping me informed :smile:.

**Comment by titusfortner** [comment]
@diemol are we supposed to be able to build examples from a different org in a PR?

**Comment by diemol** [comment]
I think I wrote the script with that in mind. I was never able to test it. Feel free to adjust.

**Pull request merged**
