### PR TITLE
Update Chinese translation of "components_of_a_grid.zh-cn.md"

### PR DESCRIPTION
**Pull request by alaahong**
- grid/grid_4/components_of_a_grid.zh-cn.md

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [X] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [X] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [X] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by alaahong** [comment]
One confused word during my translation. The "Queuer", does that mean the one who want to add into the queue? Or play the queue provider? 
In the translation, I treat as the one who want to add into the queue, please correct me if any missed.
Thanks.

**Comment by pujagani** [comment]
> One confused word during my translation. The "Queuer", does that mean the one who want to add into the queue? Or play the queue provider?
> In the translation, I treat as the one who want to add into the queue, please correct me if any missed.
> Thanks.

Thank you for your contribution. Sorry for the confusion. The "Queuer" component is the one only who can talk to the queue. It's the component that performs all actions on the queue and has access to the queue. So it would be more of a queue provider.

**Comment by harsha509** [comment]
Hi @alaahong,

Thanks for the PR.

would you like to make changes to this PR based on above comments .?

**Comment by alaahong** [comment]
> > One confused word during my translation. The "Queuer", does that mean the one who want to add into the queue? Or play the queue provider?
> > In the translation, I treat as the one who want to add into the queue, please correct me if any missed.
> > Thanks.
> 
> Thank you for your contribution. Sorry for the confusion. The "Queuer" component is the one only who can talk to the queue. It's the component that performs all actions on the queue and has access to the queue. So it would be more of a queue provider.

Thanks for your following, got the point via above detail. 
image

**Comment by alaahong** [comment]
> Hi @alaahong,
> 
> Thanks for the PR.
> 
> would you like to make changes to this PR based on above comments .?

Yes, just commit as above highlight point.
Thanks

**Review by harsha509 — APPROVED** [review]
Thank you @alaahong !

**Pull request merged**
