### PR TITLE
Upgrade selenium 4 ruby examples & rendering issue

### PR DESCRIPTION
**Pull request by aguspe**
### Description
This PR updates the upgrade to selenium 4 documentation to avoid the wrong rendering of the ruby examples and also moves the ruby examples for the before section to the options_spec file

This PR needs to be merged after #1679 

### Motivation and Context
Currently due to changes I introduced in #1668 the rendering of the ruby example in the upgrade selenium page is wrong:

Screenshot 2024-04-26 at 17 57 00

This PR fixes that and migrates the ruby example on the before tab

### Types of changes
- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist
- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by harsha509** [comment]
HI @aguspe,

Thank you for the PR.

could you please look into conflicts.

Thanks,
Sri

**Comment by aguspe** [comment]
Hi @harsha509 

Thank you for the help,
The conflicts are resolved and I also fixed the rendering of the proxy options in the docs

Let me know if everything else is needed and have a great weeekend

**Review by harsha509 — APPROVED** [review]
Thank you @aguspe !

**Comment by aguspe** [comment]
@harsha509 Thank you :) I will continue updating the ruby documentation today, have a nice day!

**Pull request merged**
