### PR TITLE
Translation of Selenium Page Object Model Section to Portuguese

### PR DESCRIPTION
**Pull request by erick-ribeiro**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

Title: Translation of Selenium Page Object Model Section to Portuguese

### Description
Translated the Selenium Page Object Model section of the documentation into Portuguese.

### Motivation and Context
The original section dealing with the Page Object Model in the Selenium documentation was still written in English. This change is required to facilitate the understanding of Brazilian Selenium users, allowing them to better utilize this test automation approach.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [X] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [X] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [X] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by luisfcorreia — COMMENTED** [review]
Hi, thanks for this translation effort.

Please fix a couple of typos and I'll accept your PR.

**Comment by luisfcorreia** [comment]
Also, please sign the CLA

**Review by luisfcorreia — CHANGES_REQUESTED** [review]
The typo:

### Vantagensc

**Comment by erick-ribeiro** [comment]
Luis Correia, I have made the corrections to the typographical errors you mentioned. Please review the changes and let me know if there is anything else I need to do. Thank you!

**Review by luisfcorreia — APPROVED** [review]
[deploy site]

**Comment by harsha509** [comment]
Thank you for the review @luisfcorreia !

**Pull request merged**
