### PR TITLE
Change Chromium to Chrome in browsers.en.md

### PR DESCRIPTION
**Pull request by armstrongsolona**
### Description
I think this is supposed to be Chrome?

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by Harsha509** [comment]
Hi @armstrongsolona ,

Good one!
Also, can you please make this change in other translated pages too!

Regards,
Harsha

**Comment by armstrongsolona** [comment]
@Harsha509  I'm not sure which other pages you mean. I will need to clone the repo and make the changes locally, which I can't do at the moment. I will come back...

**Comment by Harsha509** [comment]
Hi @armstrongsolona ,

Did you get a chance to look into above comments

Regards,
Harsha

**Comment by Harsha509** [comment]
Hi @armstrongsolona ,

Thanks for the PR. The suggested changes are landed with commit [6bccd3d](https://github.com/SeleniumHQ/seleniumhq.github.io/commit/6bccd3d4f9a6f998cd84c75acfc2c264a2c5fc14)

Regards,
Harsha

**Pull request closed without merging**
