### PR TITLE
Add code example for Python (is displayed)

### PR DESCRIPTION
**Pull request by Larsluph**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @Larsluph ,

Thank you for the PR.

Could you please do the similar changes in other translated pages too which are not in English!

**Comment by Larsluph** [comment]
@harsha509 Here it is!

**Review by harsha509 — APPROVED** [review]
Thank you @Larsluph !

**Comment by harsha509** [comment]
Congratulations on your first contribution to Selenium-docs @Larsluph 🎉 🎉 !

**Pull request merged**
