### PR TITLE
Modify: Updating selenium alpha download versions in downloads page

### PR DESCRIPTION
**Pull request by Harsha509**
### Description
Updating download versions and links for selenium alpha versions in the downloads section

### Types of changes

- [x] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by Harsha509** [comment]
> Thanks for this PR @Harsha509, but the file you'd like to change is this [one](https://github.com/SeleniumHQ/seleniumhq.github.io/blob/master/site_source_files/themes/selenium/layouts/downloads/section.html).
> Also, I think it would be better to display the current stable release and the alphas, not just replace them.
> 
> Thanks

Sure @diemol . I will do the requested changes. Also can you please let me know how to check the changes with hugo for downloads section. 

Regards,
Harsha

**Comment by diemol** [comment]
@Harsha509 it mentioned here
https://selenium.dev/documentation/en/contributing/#step-3-make-changes

You just need to go to the site source files directory and start hugo.

**Comment by Harsha509** [comment]
> @Harsha509 it mentioned here
> https://selenium.dev/documentation/en/contributing/#step-3-make-changes
> 
> You just need to go to the site source files directory and start hugo.

Apologies, I missed it. Thanks @diemol. will do the requested changes.

**Comment by Harsha509** [comment]
After:
after

**Comment by Harsha509** [comment]
Thanks for the review @diemol

**Pull request merged**
