### PR TITLE
Re-organizing the page "Types of testing"

### PR DESCRIPTION
**Pull request by Catalin-Negru**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

Re-organizing the page "Types of testing"

### Description
Some of the things in this page were not quite accurate and some can be improved. So...

(1) Improved hierarchies: 
- Made Functional testing a level 2 header.
- Created Non-Functional Testing as a level 2 header.
- Moved Acceptance Testing and Regression testing as level 3 headers below Functional Testing.
- Made TDD and BDD level 2 headers.
- 
(2) Removed and added information:
- Deleted a sentence from Acceptance Testing
- Deleted Performance Testing header and information since this would create a single lvl 2 header, followed by a single lvl 3 header followed two lvl 4 headers.
- specified that Load Testing and Stress Testing are part of Performance Testing.

(3) Split the page in two:
- specified through a bold-italic sentence that Functional Testing and Non-Functional Testing are **test types**.
- Specified through a bold-italic sentence and a line above that TDD and BDD are **test methods** specific to Agile.

### Motivation and Context
- Desire for accuracy.
- Willing to help; I use Selenium a lot.

### Types of changes

- [x] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by diemol — COMMENTED** [review]
Thank you for this PR, @Catalin-Negru. 

However, please note that this page is translated to several other languages. Therefore, we would need to have the same structure in the translations, and any new comment or edit needs to be properly insterted in the translated pages.

Probably reorganising is a good idea, but I do not see much value in the added comments. 

If you'd like, we can take this PR if it sticks to the reorganization part only and the same structure is applied to the translated pages. What do you think?

**Comment by Catalin-Negru** [comment]
Hi @diemol . 
Thank you for your comment.

**1. I thought it was better to test the waters only with the English page,** and then, IF and AFTER the changes were approved, to suggest them to the other language pages as well. Next time I'll know to suggest changes to all of them at the same time.

**2. I agree with your last sentence.** It is not clear to me if me or someone else needs to do additional actions in this regard. Please instruct me if I have to do something.

All the best.

**Comment by diemol** [comment]
>2. I agree with your last sentence. It is not clear to me if me or someone else needs to do additional actions in this regard. Please instruct me if I have to do something.

Great! 

The idea would be to apply the same structure to the other files, with this, we do not need to revert any translations. Would be nice if that can be included in this PR as well. Thanks!

**Comment by Catalin-Negru** [comment]
Hi @diemol .

I will close this pull request and I'll make a new one for all pages as you instructed in the first comment, which will include only the structural changes.

**Pull request closed without merging**
