### PR TITLE
Update install_drivers.en.md

### PR DESCRIPTION
**Pull request by fristzzz**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

fixed the code in the WebDriver -- Getting Started -- Install Drivers -- 3.Hard Coded Location of Documentation
### Motivation and Context

when running previous code `const service = new chrome.ServiceBuilder('/path/to/chromedriver').build();` 
with node.js:
 *throw TypeError('not a chrome.ServiceBuilder object')*

after adding `const chrome = require('selenium-webdriver/chrome')`, it throws another error:
*throw TypeError('not a chrome.ServiceBuilder object')*

after deleting `.build()`, it runs correctly

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by diemol — DISMISSED** [review]
Could you please add these changes to the files:

- install_drivers.ja.md
- install_drivers.pt-br.md
- install_drivers.zh-cn.md

**Comment by harsha509** [comment]
Hi @fristzzz ,

Hope you're doing well.

Did you get a chance to look into above comments ?

**Comment by fristzzz** [comment]
> Hi @fristzzz ,
> 
> Hope you're doing well.
> 
> Did you get a chance to look into above comments ?

@harsha509  @diemol 
I've added the changes, please check them out :)

**Review by harsha509 — APPROVED** [review]
Thank you @fristzzz !

**Review by harsha509 — APPROVED** [review]

**Pull request merged**
