### PR TITLE
doc: fix typo in typographical_conventions.*.md

### PR DESCRIPTION
**Pull request by HollowMan6**
### Description
Gratutious -> Gratuitous

### Motivation and Context
Fix typo

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [X] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [X] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [X] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @HollowMan6 ,

Thanks for the PR.

Can you please make same changes in other translated pages which are in english> (like es, zh-cn etc).

Thanks!

**Comment by HollowMan6** [comment]
> Hi @HollowMan6 ,
> 
> Thanks for the PR.
> 
> Can you please make same changes in other translated pages which are in english> (like es, zh-cn etc).
> 
> Thanks!

@JS31096  done!

**Review by harsha509 — APPROVED** [review]
Thank you @HollowMan6 !

**Comment by harsha509** [comment]
:tada::tada: Congratulations on your first contribution @HollowMan6 :tada::tada:

**Pull request merged**
