### PR TITLE
Migration to hugo module

### PR DESCRIPTION
**Pull request by deining**
Following up on #1308, this PR converts the site to hugo modules. You have come pretty far with the conversion already!
The problems you enountered were due to the fact that your project specific file `/assets/scss/_colors.scss` overwrote the colors defined in the docsy theme. Since only a subset of all colors needed was defined in your file, the build failed. I change the file name to `_colors_project.sccs` and imported this file. Afterwards the site in up and running and looks fairly good to me.

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by diemol — APPROVED** [review]
This is great, thank you @deining!

**Review by diemol — COMMENTED** [review]
I'll merge this but I will need to adjust the GitHub workflows first before publishing again.

**Comment by deining** [comment]
I'm glad I could help out here. One last observation: can't we remove this line, too?

https://github.com/SeleniumHQ/seleniumhq.github.io/blob/34b940e0a20ad8a0e182bc040f2414db349b5465/build-site.sh#L35

**Comment by diemol** [comment]
> I'm glad I could help out here. One last observation: can't we remove this line, too?
> 
> https://github.com/SeleniumHQ/seleniumhq.github.io/blob/34b940e0a20ad8a0e182bc040f2414db349b5465/build-site.sh#L35

Yes, I missed it.

**Pull request merged**
