### PR TITLE
Browser chrome binary java sample

### PR DESCRIPTION
**Pull request by santoshhawle**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description
Java sample code added in documentation & sample for chrome to Start browser in a specified location

### Motivation and Context
- There is no example of **Java Start browser in a specified location** in the documentation

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by titusfortner** [comment]
The goal of putting these in the github repo is so that they will pass.

What we need to do is to get the binary installed somewhere (probably using DriverFinder class) and then reference that location in the code.

**Comment by santoshhawle** [comment]
Hi @titusfortner I have added code to get the binary location at runtime and referenced that location in the code.

**Comment by harsha509** [comment]
Hi @santoshhawle ,

* Can you add similar changes in other translated pages with are other than in English?
* can you work on resolving the conflicts too?


Thanks,
Sri

**Comment by titusfortner** [comment]
Thanks for this code, but I ended up adding it in all the languages a few weeks ago — https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/java/src/test/java/dev/selenium/browsers/ChromeTest.java#L58-L65

**Comment by harsha509** [comment]
Hi @santoshhawle ,

Thank you for looking into this and raising the PR!

Looks like the changes have landed with commit https://github.com/SeleniumHQ/seleniumhq.github.io/commit/efe4c5a0ad4a664682f3f7bcb61c92a101754188. 

Thanks,
Sri

**Pull request closed without merging**
