### PR TITLE
[Docs] Added instructions for Java in the 'Test Runners' section

### LINKED ISSUE #1457: [🚀 Feature]: Add instructions for Java in the 'Test Runners' section
### Feature and motivation

There are currently no instructions in the [Test Runners](https://www.selenium.dev/documentation/webdriver/getting_started/first_script/#test-runners) section for Java. I would like to add the following:

---

Install and execute JUnit 5 test runner using a build tool.

### Maven

In the project’s `pom.xml` file, specify the dependency: 

```
<dependency>
    <groupId>org.junit</groupId>
    <artifactId>junit-bom</artifactId
    <version>5.10.0</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>

<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter</artifactId>
    <scope>test</scope>
</dependency>
```

and specify the build plugin:

```
<plugin>
    <artifactId>maven-surefire-plugin</artifactId
    <version>3.1.2</version>
</plugin>
```

Now, run your tests using:

```
mvn clean test
```

### Gradle

In the project's `build.gradle` file,  specify the dependency: 

```
testImplementation platform('org.junit:junit-bom:5.10.0')
testImplementation 'org.junit.jupiter:junit-jupiter'
```

and add the following in the `test` task:

```
useJUnitPlatform()
```

Now, run your tests using:

```
gradle clean test
```

### PR DESCRIPTION
**Pull request by Tahanima**
Fixes #1457

### Description
This PR adds instructions to setup JUnit 5 as a test runner for Java. 

### Motivation and Context
There are currently no instructions for Java. So, I've included it.

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by Tahanima** [comment]
@titusfortner, the 2 failures are unrelated to my PR.

**Comment by diemol** [comment]
Can you please add the same for the other `first_script.*.md` files?

**Comment by Tahanima** [comment]
> Can you please add the same for the other `first_script.*.md` files?

Sure, I will.

**Comment by Tahanima** [comment]
@diemol I've added the same changes  for the other `first_script.*.md` files.

**Review by diemol — APPROVED** [review]
Great, thank you @Tahanima!

**Comment by Tahanima** [comment]
> Great, thank you @Tahanima!

You're welcome @diemol

**Pull request merged**
