### PR TITLE
Add info for vscode, C#, and .NET SDK

### PR DESCRIPTION
**Pull request by tarekahf**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Add the related details for using vs code and C# with the supported .NET SDK Version.

### Motivation and Context

I spent a lot of time trying to use vscode and C#. I wanted to help others save time.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)
- [x] Added new sections for getting started for using vscode, C#, and .NET SDK.

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by harsha509 — COMMENTED** [review]
Hi @tarekahf,

Thank you for providing the PR.

1. Could you please add the changes in other translated pages too. See [Contributing guidelines](https://www.selenium.dev/documentation/about/contributing/)


2. As this is specific to .NET, can we move it to C# Section ?  @diemol, @titusfortner any suggestions on this ?

**Comment by tarekahf** [comment]
> 1. Could you please add the changes in other translated pages too. See [Contributing guidelines](https://www.selenium.dev/documentation/about/contributing/)

Yes, sure. I will translate to the same existing languages in the project, namely: en, ja, pt-br, zh-cn, correct? First, I will finalize the English Language Version.

> 2. As this is specific to .NET, can we move it to C# Section?  @diemol, @titusfortner any suggestions on this?

Yes, I can do that. 

Please, let me know if you have any other comments.

Tarek

**Comment by tarekahf** [comment]
Hi @harsha509,

I have moved the update to be under the C# Section. Please let me know if you have any other comments.

**Comment by tarekahf** [comment]
Hi @harsha509 , I am just wondering why there was no another deploy preview for the changes I made? How is this triggered?

**Comment by diemol** [comment]
@tarekahf 

>Yes, sure. I will translate to the same existing languages in the project, namely: en, ja, pt-br, zh-cn, correct? First, I will finalize the English Language Version.

There is no need to translate the content, only to put the English content on the other pages.

**Comment by diemol** [comment]
> Hi @harsha509 , I am just wondering why there was no another deploy preview for the changes I made? How is this triggered?

Maybe because the PR was closed and opened again. However, if you check the deploy link, the content is up to date with the latest commit.

**Comment by tarekahf** [comment]
Thanks, @diemol 

> There is no need to translate the content, only to put the English content on the other pages.

Sure, I will do that soon.

So, after I do the other languages as mentioned, it will be merged to the main branch, and the changes will be live?

**Comment by harsha509** [comment]
Hi @tarekahf ,

Did you get a chance to look into above comments and add the same content in other translated pages ?

Once you do the modifications in other translated pages and then we merge and changes will be live in around ~5min

**Comment by tarekahf** [comment]
> Hi @tarekahf ,
> 
> Did you get a chance to look into above comments and add the same content in other translated pages ?
> 
> Once you do the modifications in other translated pages and then we merge and changes will be live in around ~5min

Hi @harsha509,

Sorry for the delay ... I honestly admire all those who work on such projects for free. I cannot find the time to complete such a small change. I am working on it now...

**Comment by tarekahf** [comment]
Hi @harsha509,

I have added the changes to all 4 languages as requested. All changes committed to the sea branch 'patch-3'.

Please let me know if you require additional info.

Regards,
Tarek

**Review by harsha509 — APPROVED** [review]
Thank you @tarekahf !

**Comment by harsha509** [comment]
Congratulations on your first contribution to Selenium Docs @tarekahf 🎉 🎉 !

**Comment by tarekahf** [comment]
> Congratulations on your first contribution to Selenium Docs @tarekahf 🎉 🎉 !

Thank you @harsha509 ... I feel like I want to party now!

**Pull request merged**
