### PR TITLE
Update remote_webdriver.en.md

### PR DESCRIPTION
**Pull request by ahndmal**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

Fix Kotlin code issues in examples

### Description
Fix Kotlin code issues in examples as it is incorrect.

### Motivation and Context

Fix the issues

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by diemol — COMMENTED** [review]
Can you please change this on the `remote_webdriver.ja.md`, `remote_webdriver.pt-br.md`, and `remote_webdriver.zh-cn.md` files?

**Comment by ahndmal** [comment]
Hello @diemol !
Thank you for the review :) Added the changes.

**Comment by diemol** [comment]
@ahndmal I only see changes done to one file, the other 3 are missing.

**Comment by diemol** [comment]
It seems you made the changes on `trunk` in your fork, not the branch used for this PR.

**Comment by ahndmal** [comment]
@diemol , yes, sorry for that :( applied changes to patch-1. Seems like they are visible now in this PR.

**Review by diemol — APPROVED** [review]

**Pull request merged**
