### PR TITLE
Add Brazilian Portuguese (pt-br) docs translations

### PR DESCRIPTION
**Pull request by effeix**
Complete files and folders under `docs_source_files/content/`:
```
- _index.pt-br.md
- CONTRIBUTING.pt-br.md
- driver_idiosyncrasies/*
- front_matter/*
- getting_started/*
- getting_started_with_webdriver/*
- grid/*
- guidelines_and_recommendations/*
- introduction/*
- remote_webdriver/*
- selenium_installation/*
- worst_practices/*
- legacy_docs/* except selenium_rc.pt-br.md
- support_packages/_index.pt-br.md
- support_packages/chrome_devtools.pt-br.md
- webdriver/_index.pt-br.md
- webdriver/http_proxies.pt-br.md
- webdriver/page_loading_strategy.pt-br.md
- webdriver/support_classes.pt-br.md
```

Incomplete files and folders under `docs_source_files/content/`:
```
- legacy_docs/selenium_rc.pt-br.md
- support_packages/mouse_and_keyboard_actions_in_detail.pt-br.md
- support_packages/working_with_cookies.pt-br.md
- support_packages/working_with_select_elements.pt-br.md
- webdriver/browser_manipulation.pt-br.md
- webdriver/driver_requirements.pt-br.md
- webdriver/js_alerts_prompts_and_confirmations.pt-br.md
- webdriver/keyboard.pt-br.md
- webdriver/understanding_the_components.pt-br.md
- webdriver/waits.pt-br.md
- webdriver/web_element.pt-br.md
```

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [x] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by effeix** [comment]
Hi @diemol! I've just seen that the pipeline failed and viewing its details it seems to be something wrong with the Twitter API - Service Unavailable. Am I able to run the pipeline again? To check if it passes, because maybe it was something temporary.

**Comment by harsha509** [comment]
HI @gustavoefeiche,

Re-ran the Job, the build passes now. Will review and get it merged!

**Review by harsha509 — APPROVED** [review]
Thank you @gustavoefeiche!

**Comment by harsha509** [comment]
Deploy preview looks good!

**Comment by effeix** [comment]
Thank you for accepting @JS31096! My pleasure to contribute :)

**Pull request merged**
