### PR TITLE
Added se-config.toml Example to Selenium Manager

### PR DESCRIPTION
**Pull request by shbenzer**
### **User description**
Added se-config.toml example to Documentation.

### Description
created example_se-config.toml
added example to all translations of Selenium Manager

### Motivation and Context
Extends Issue #1496 , will now add what language bindings are available as well.

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

___

### **PR Type**
Documentation

___

### **Description**
- Added an example `se-config.toml` file for Selenium Manager with various configuration options.
- Updated documentation in multiple languages (English, Japanese, Portuguese, Chinese) to include the `se-config.toml` example.
- Enhanced documentation to help users understand how to configure Selenium Manager using a TOML file.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>example_se-config.toml</strong><dd><code>Add example `se-config.toml` for Selenium Manager</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

examples/python/tests/selenium_manager/example_se-config.toml

<li>Added a new example configuration file for Selenium Manager.<br> <li> Configures various settings like browser, driver, and paths.<br> <li> Includes options for proxy, timeout, and debugging.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1991/files#diff-b30e813e756076c90239fe30e5facdb2f3d9af6cf7009827cf85b2aca8e53600">+21/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>selenium_manager.en.md</strong><dd><code>Add `se-config.toml` example to English documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

website_and_docs/content/documentation/selenium_manager.en.md

<li>Added a section for <code>se-config.toml</code> example.<br> <li> Linked to the example configuration file.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1991/files#diff-abfd3399fa93ee23ed8a6b8637b566cf12c67d477fda705ed877a10f013047b7">+7/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>selenium_manager.ja.md</strong><dd><code>Add `se-config.toml` example to Japanese documentation</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

website_and_docs/content/documentation/selenium_manager.ja.md

<li>Added a section for <code>se-config.toml</code> example.<br> <li> Linked to the example configuration file.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1991/files#diff-a84369b32708be4deb5da8f23f5b2c0adecb18e5eee5d30601e96f5d75e999f0">+7/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>selenium_manager.pt-br.md</strong><dd><code>Add `se-config.toml` example to Portuguese documentation</code>&nbsp; </dd></summary>
<hr>

website_and_docs/content/documentation/selenium_manager.pt-br.md

<li>Added a section for <code>se-config.toml</code> example.<br> <li> Linked to the example configuration file.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1991/files#diff-d8c0fd932e504044c81c242c7e255cb4533a7ea66e2b12d142c1cbb1680f6213">+7/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>selenium_manager.zh-cn.md</strong><dd><code>Add `se-config.toml` example to Chinese documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

website_and_docs/content/documentation/selenium_manager.zh-cn.md

<li>Added a section for <code>se-config.toml</code> example.<br> <li> Linked to the example configuration file.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1991/files#diff-7b85ea66160081776015671c1e38dda6f8fd556f1217683dff9a0982fa71fc2b">+7/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by shbenzer** [comment]
@VietND96 Fails are due to flaky tests:

(macos, stable)
> FAILED tests/browsers/test_safari.py::test_basic_options - TypeError: __init__() missing 1 required positional argument: 'remote_server_addr'
FAILED tests/browsers/test_safari.py::test_enable_logging - TypeError: __init__() missing 1 required positional argument: 'remote_server_addr'

and (macos, nightly)

> FAILED tests/drivers/test_options.py::test_timeouts_page_load - selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: -0.050
  (Session info: chrome=130.0.6723.92)
Stacktrace:
0   chromedriver                        0x000000010074b648 cxxbridge1$str$ptr + 3645404
1   chromedriver                        0x0000000100743ea8 cxxbridge1$str$ptr + 3614780
2   chromedriver                        0x00000001001b0104 cxxbridge1$string$len + 88416
3   chromedriver                        0x000000010019b704 cxxbridge1$string$len + 3936
4   chromedriver                        0x000000010019b48c cxxbridge1$string$len + 3304
5   chromedriver                        0x000000010019983c core::str::slice_error_fail::h1cab30ac4b13c655 + 60316
6   chromedriver                        0x0000000100199f04 core::str::slice_error_fail::h1cab30ac4b13c655 + 62052
7   chromedriver                        0x00000001001a779c cxxbridge1$string$len + 53240
8   chromedriver                        0x00000001001ba600 cxxbridge1$string$len + 130652
9   chromedriver                        0x000000010019a508 core::str::slice_error_fail::h1cab30ac4b13c655 + 63592
10  chromedriver                        0x00000001001ba498 cxxbridge1$string$len + 130292
11  chromedriver                        0x000000010022bb10 cxxbridge1$string$len + 594796
12  chromedriver                        0x00000001001e6f54 cxxbridge1$string$len + 313264
13  chromedriver                        0x00000001001e7ba4 cxxbridge1$string$len + 316416
14  chromedriver                        0x00000001007161e8 cxxbridge1$str$ptr + 342[719](https://github.com/SeleniumHQ/seleniumhq.github.io/actions/runs/11682156836/job/32528707624?pr=1991#step:11:720)6
15  chromedriver                        0x000000010071952c cxxbridge1$str$ptr + 3440320
16  chromedriver                        0x00000001006fd60c cxxbridge1$str$ptr + 3325856
17  chromedriver                        0x0000000100719df0 cxxbridge1$str$ptr + 3442564
18  chromedriver                        0x00000001006ee890 cxxbridge1$str$ptr + 3265060
19  chromedriver                        0x0000000100734898 cxxbridge1$str$ptr + 3551788
20  chromedriver                        0x0000000100734a14 cxxbridge1$str$ptr + 3552168
21  chromedriver                        0x0000000100743b40 cxxbridge1$str$ptr + 3613908
22  libsystem_pthread.dylib             0x0000000183e55f94 _pthread_start + 136
23  libsystem_pthread.dylib             0x0000000183e50d34 thread_start + 8

**Comment by VietND96** [comment]
I am thinking that beside the TOML config with explanation, should we add another example TOML so that user can get started quickly in their trial?
What do you think @harsha1502 @diemol ?

**Review by A1exKH — CHANGES_REQUESTED** [review]
@shbenzer  Code LGTM.
Please fix failed checks.

**Comment by harsha509** [comment]
> I am thinking that beside the TOML config with explanation, should we add another example TOML so that user can get started quickly in their trial? What do you think @harsha1502 @diemol ?

Hi @VietND96,

Yes, It would be great if we could provide code samples or boilerplate code to help users get started more easily.

I also think that the page [Selenium Manager Documentation](https://www.selenium.dev/documentation/selenium_manager/) is quite extensive and could benefit from being split into `multiple sections`. We can consider adding a dedicated "Getting Started" section to make it easier for users to navigate and find essential information.

Let me know what you think!

**Comment by shbenzer** [comment]
> @shbenzer Code LGTM. Please fix failed checks.

contributed code is only a .toml and documentation.

**Review by VietND96 — APPROVED** [review]

**Comment by VietND96** [comment]
I agreed to split it into multiple sections. So we will merge this first and improve later.

**Comment by VietND96** [comment]
Thank you, @shbenzer !

**Pull request merged**
