### PR TITLE
Update waits.zh-cn.md

### PR DESCRIPTION
**Pull request by yingyingshang**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [x] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by Harsha509** [comment]
hi @yingyingshang ,

Thanks for the PR. can you please complete the above 'checklist' and 'types of changes' for this PR

**Comment by yingyingshang** [comment]
Hi @Harsha,
I do not know how to check them by using hugo to render the site/docs locally, could you help on that?
Thanks.

**Comment by Harsha509** [comment]
> Hi @harsha,
> I do not know how to check them by using hugo to render the site/docs locally, could you help on that?
> Thanks.

Hi @yingyingshang ,

Sure, you have to just follow the contribution guidelines. It has precise steps, here is the link https://selenium.dev/documentation/en/contributing/

Thanks,
Harsha

**Comment by yingyingshang** [comment]
Hi Harsha,
I have used hugo to render the site/docs locally and I am sure it works.

Regards,
Yingying

**Pull request merged**
