### PR TITLE
typo fix in capability

### PR DESCRIPTION
**Pull request by boris779**
### Description
german translation for first steps and the regarding champter driver_idiosyncrasies including the subpages.

### Motivation and Context
to complete german translation

### Types of changes
- [x] Change to the site (only a typo!)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist
- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by harsha509 — APPROVED** [review]
Thank you @boris779 !

**Comment by harsha509** [comment]
HI @boris779 ,

Can you please resolve the conflict!

Thanks!

**Review by harsha509 — CHANGES_REQUESTED** [review]
Conflict!

**Comment by boris779** [comment]
Sorry I did the change in the wrong file. I will do it again.

**Pull request closed without merging**
