### PR TITLE
Added explanation that 'Relative Locators' is not available in the current stable release.

### PR DESCRIPTION
**Pull request by honjiaxuan**
Added explanation that 'Relative Locators' is not available in the current stable release in docs_source_files/content/webdriver/locating_elements.en.md and all its other language files.

### Description

I added a short paragraph to explain that "Relative Locators" are not available in the current stable release (Selenium 3), anyone that want to use that feature have to install Selenium 4 and latest available version is mentioned as well.

### Motivation and Context

The current documentation didn't tell the users that the stable release they installed is Selenium 3 instead of Selenium 4. But "Relative Locators" only available in Selenium 4.

### Types of changes

- [x] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by luke-hill** [comment]
Hi @honjiaxuan 

There appears to be some auto-formatting bug with your IDE that has caused a load of methods to be shifted out of line. Could you check maybe your local editorconfig and maybe try revert those changes?

**Review by diemol — CHANGES_REQUESTED** [review]
This PR creates more maintenance than rather clarifying things. 

I'd be ok with a comment next to the **Selenium 4** text above that says something like "be sure to be on Selenium 4 to use relative locators".

**Comment by diemol** [comment]
@honjiaxuan, would you like to continue with this PR based on the commend I made above?

**Comment by harsha509** [comment]
Closing this as we didn’t hear back from the OP.

**Pull request closed without merging**
