### PR TITLE
Update waits.en.md: Corrected the mistake in example of Explicit wait in Java program 

### PR DESCRIPTION
**Pull request by veerendrajana**
updated the Explicit wait example with By.tagName. Currently, it is showing By.name('q') which will not exist in race condition example.

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

Explicit wait example is wrong. It is showing By.name("q"), it should be By.tagName("p");

### Types of changes

- [yes ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by diemol** [comment]
Please update the files in the other spoken languages, not only the `.en.` file.

**Comment by veerendrajana** [comment]
updated remanining 4 languages as well

**Comment by diemol** [comment]
@veerendrajana I still see changes only on the `.en.` file.

**Comment by veerendrajana** [comment]
Now, I modified affected 4 files. Please review them. Thank you.

**Review by diemol — APPROVED** [review]

**Pull request merged**
