### PR TITLE
Fixed incorrect variable name in C# example

### PR DESCRIPTION
**Pull request by dutts**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
The after C# example showed the driver being initiated with a missing parameter called `options`, the object being built in the example is called `browserOptions` so have updated the example to save confusion.

### Motivation and Context
Fixes documentation

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by dutts** [comment]
Not quite sure how my change broke all your workflows.

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @dutts,

Thanks for the PR. Could you please do the similar changes in other translated pages

**Comment by dutts** [comment]
> Hi @dutts,
> 
> Thanks for the PR. Could you please do the similar changes in other translated pages

Done

**Review by harsha509 — APPROVED** [review]
Thank you @dutts !

**Pull request merged**
