### PR TITLE
Adds documentation and examples for relative locator usage.

### PR DESCRIPTION
**Pull request by AutomatedTester**
### Description
This adds documentation and examples for the new Relative Locators feature in Selenium 4

### Motivation and Context
Documentation was missing

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by diemol — COMMENTED** [review]
@AutomatedTester. seems that documentation for relative locators already exists here https://www.selenium.dev/documentation/en/getting_started_with_webdriver/locating_elements/#relative-locators.

Should we merge some of this content of this PR to that page or should we close this PR?

**Comment by AutomatedTester** [comment]
I wonder if having it in both places would be good. Since I would expect to find details of locators with its relevant findElement commands. Or at least in my head. Let’s discuss on Monday

**Comment by AutomatedTester** [comment]
@diemol I have moved the documentation as we discussed on Slack this week. Let me know if you want further improvements.

**Review by harsha509 — APPROVED** [review]
Thank you @AutomatedTester !

**Pull request merged**
