### PR TITLE
Update keyboard.en.md

### PR DESCRIPTION
**Pull request by pauljones0**
Added Python action chain send_keys example and removed comments

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by pauljones0** [comment]
Let me know if I need to make any changes. I noticed that code examples are supposed to be posted and linked from the code examples on Github, but I'm not sure how to do that exactly.

As for language translation, I removed all comments to as I wasn't planning on translating to different languages.

**Review by diemol — CHANGES_REQUESTED** [review]
Can you please add this to the other `keyboard.*.md` files?

**Comment by pauljones0** [comment]
Okay, I think it's all in order now. I added the example to all keyboard*.md languages.

If I messed it all up too much (I pushed here and pushed there), feel free to let me know.

**Review by diemol — APPROVED** [review]
Thank you, @pauljones0!

**Pull request merged**
