### PR TITLE
added javascript code block for "Fetching Attributes or Properties"

### PR DESCRIPTION
**Pull request by sridhar-5**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description
This Pull Request contains missing code block of the javascript documentation for Fetching Attributes or Properties of selenium webdriver.

### Motivation and Context

Screenshot 2023-01-17 at 3 42 53 PM
The following pull request when successfully merged should fill in the slot shown in the above screenshot. you can find it  
 [**here**](https://www.selenium.dev/documentation/webdriver/elements/information/) .

### Types of changes

- [x ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @sridhar-5 ,

Thank you for the PR.

Can you add the changes in other translated pages too, which are other than in english!

**Comment by sridhar-5** [comment]
Sure @harsha509 .

**Comment by sridhar-5** [comment]
Done @harsha509. can you review now ?

**Review by harsha509 — APPROVED** [review]
Thank you @sridhar-5 !

**Comment by sridhar-5** [comment]
How can one be the member of selenium community @harsha509 ?

**Comment by harsha509** [comment]
Congratulations on your first contribution to Selenium-docs @sridhar-5  🎉 🎉 🎉

**Comment by sridhar-5** [comment]
Thanks mate..!

**Comment by harsha509** [comment]
Sure,

here is the governance document for it ! https://www.selenium.dev/project/governance/

**Pull request merged**
