### PR TITLE
Added Python Examples to Organizing and Executing Selenium Code

### PR DESCRIPTION
**Pull request by shbenzer**
### **User description**
Added Execution Example to Organizing and Executing Selenium Code

### Description
Updated english and japanese versions of Organizing and Executing Selenium Code page to include lines of python code for execution

### Motivation and Context
needed documentation

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

___

### **PR Type**
Documentation, Enhancement

___

### **Description**
- Added `setup` and `teardown` functions in `using_selenium_tests.py` to manage WebDriver lifecycle.
- Updated English and Japanese documentation to include Python setup and teardown examples.
- Enhanced documentation to provide clearer guidance for Python Selenium tests.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>using_selenium_tests.py</strong><dd><code>Add setup and teardown functions for Selenium tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

examples/python/tests/getting_started/using_selenium_tests.py

<li>Added <code>setup</code> function to initialize the WebDriver and open a URL.<br> <li> Added <code>teardown</code> function to quit the WebDriver.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1869/files#diff-aa8c2cd4492a49444ef99b560ecda82475b27fc52ef5804d99b186c4a8c1bddc">+8/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>using_selenium.en.md</strong><dd><code>Update English documentation with Python examples</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/getting_started/using_selenium.en.md

<li>Added Python setup and teardown code examples.<br> <li> Updated documentation to include Python-specific instructions.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1869/files#diff-f521d4cd05fea84ac0fd18184a214f8ac2cd023a7f2c1a7e2b43495504b7b9f0">+10/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>using_selenium.ja.md</strong><dd><code>Update Japanese documentation with Python examples</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/getting_started/using_selenium.ja.md

<li>Added Python setup and teardown code examples.<br> <li> Updated Japanese documentation to include Python-specific <br>instructions.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1869/files#diff-53fac7bfd25fb50de7731415fedc5ea636bcdaa83166f476b3c9e13a691a6c7c">+10/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by diemol** [comment]
Is this PR duplicating #1868?

**Comment by shbenzer** [comment]
@diemol It seems that each of my 4 PRs includes the previous in it

**Comment by diemol** [comment]
OK, so please either split them or have a single one. 

For the future, it is better to have separate change sets.

**Comment by shbenzer** [comment]
@diemol Would you like me to cancel all of these prs and merge them into one?

**Comment by diemol** [comment]
#1868 was merged.

**Comment by diemol** [comment]
Is that not needed in the other files?

**Comment by shbenzer** [comment]
I'm just ensuring that the merge will be easier at the end - I didn't remove any commits from the pr

**Comment by diemol** [comment]
Why are only the Japanese and English files changed?

**Comment by shbenzer** [comment]
I'll fix the remaining two prs

**Pull request closed without merging**
