### PR TITLE
Changes proposed to fix issue

### LINKED ISSUE #1279: [🚀 Feature]: Documentation improvement: https://www.selenium.dev/documentation/test_practices/discouraged/two_factor_authentication/
### Feature and motivation

The article should mention, that it might be possible to ask developers, for creation of a "non-expiry special 2fa token" created for test team, so that the journey is still testable without disabling 2FA. That way you might turn someones attention that such possibility exists, rather than closing their attention on the fact that disabling is the only option

https://www.selenium.dev/documentation/test_practices/discouraged/two_factor_authentication/

current: the only options mentioned for 2FA are to disable the 2FA
expected: The article should mention, that it might be possible to ask for a "non-expiry special 2fa token" created for test team, so that the journey is still testable without disabling 2FA. That way you might turn someones attention that such possibility exists, rather than closing their attention on the fact that disabling is the only option

Two Factor Authentication
Two Factor Authentication (2FA) is an authorization mechanism where a One Time Password (OTP) is generated using “Authenticator” mobile apps such as “Google Authenticator”, “Microsoft Authenticator” etc., or by SMS, e-mail to authenticate. Automating this seamlessly and consistently is a big challenge in Selenium. There are some ways to automate this process. But that will be another layer on top of our Selenium tests and not as secure. So, you should avoid automating 2FA.

There are few options to get around 2FA checks:

Ask your team to create a "special token" that will work in test environment, so that the functionality is still tested, just no need to use mobile device
Disable 2FA for certain Users in the test environment, so that you can use those user credentials in the automation.
Disable 2FA in your test environment.
Disable 2FA if you login from certain IPs. That way we can configure our test machine IPs to avoid this.

### PR DESCRIPTION
**Pull request by justnpT**
https://github.com/SeleniumHQ/seleniumhq.github.io/issues/1279

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by luisfcorreia** [comment]
Let me propose a better approach, this is a good recommendation for Encouraged Practices, with a note here.

**Comment by justnpT** [comment]
@luisfcorreia I'm not sure if you asked me to do something or you just made a comment that doesn't require any action

**Comment by diemol** [comment]
@justnpT could you please sign the CLA so we get this merged?

**Comment by justnpT** [comment]
> @justnpT could you please sign the CLA so we get this merged?

done

**Review by diemol — APPROVED** [review]
Thank you, @justnpT!

**Pull request merged**
