### PR TITLE
Update first_script.py

### PR DESCRIPTION
**Pull request by kevinanewman**
Apparently submit_button.click() should be submit_button.submit()

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by mmonfared** [comment]
@kevinanewman This is the very first test. Although `submit()` works, I do believe we should include at least one `click()` here for demonstration purposes and to familiarize the reader with it.

**Comment by kevinanewman** [comment]
Ok, `click()` by itself didn't seem to do anything, and didn't submit the form (unlike "clicking" the actual button with an actual mouse on the actual web page).  But `submit()` behaved as though clicking the button manually. 

Without a `submit()`, nothing happens, at least for me anyway.

**Comment by mmonfared** [comment]
> Ok, `click()` by itself didn't seem to do anything, and didn't submit the form (unlike "clicking" the actual button with an actual mouse on the actual web page). But `submit()` behaved as though clicking the button manually.
> 
> Without a `submit()`, nothing happens, at least for me anyway.

Actually, it submits. The reason you might think nothing happened is because the driver quits immediately. If we pause before `driver.quit()`, you can see this confirmation page:

image

Also, I think it would be better to have an assertion here and keep this page visible for users by a simple sleep. So I would suggest adding these lines before `driver.quit()`:

```python
assert  text == "Received!"
sleep(1) # For demo purpose
```

**Review by diemol — COMMENTED** [review]
These tests are executed daily and they are currently passing: https://github.com/SeleniumHQ/seleniumhq.github.io/actions/runs/7996701078. Why do you think it needs to be changed?

**Comment by kevinanewman** [comment]
Well, that's interesting.  I wonder if maybe there should be a delay after editing the text box so you can see that it actually happened.  When I observed the `click()` apparently not working, I was executing the lines one at a time, not running the full script all at once.  When I run the full script using `webdriver.Chrome()` the script runs and the window disappears, when I use `webdriver.Safari()` the window stays open and shows `Received!`.  

So everything does appear to be working, although there are some subtleties apparently!  I can close this PR if you like.

**Comment by diemol** [comment]
Yeah, I think we won't add this change as our CI passes.

**Comment by kevinanewman** [comment]
Ok, thank you for your time and assistance!

**Pull request closed without merging**
