### PR TITLE
Replace card blocks with separate code blocks

### PR DESCRIPTION
**Pull request by konflic**
Updated cardpanes for new version of code markup.

Before
image

After
image

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by konflic** [comment]
Before
image

After
image

**Comment by titusfortner** [comment]
Looks like the formatting of the cards didn't survive the Hugo upgrade?

**Review by diemol — CHANGES_REQUESTED** [review]
There is no need to remove the cards, we need to adjust to the changes in the recent release
https://www.docsy.dev/docs/adding-content/shortcodes/#shortcode-card-programming-code

@konflic would you like to do this change? Thank you.

**Comment by konflic** [comment]
> There is no need to remove the cards, we need to adjust to the changes in the recent release https://www.docsy.dev/docs/adding-content/shortcodes/#shortcode-card-programming-code
> 
> @konflic would you like to do this change? Thank you.

yes, will add this fix here shortly.

**Review by diemol — APPROVED** [review]

**Comment by diemol** [comment]
Thank you!

**Pull request merged**
