### PR TITLE
updated sample graphql curl command to get URI

### PR DESCRIPTION
**Pull request by sahajamit**
The graphql curl command was not working as there is no resource like "url" under grid so we have to change it to "uri"

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [x] Change to the site (I am attaching a screenshot showing the before and after)
**Before Image:**
before
**After Image**
after

- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @sahajamit,

Thanks for the PR!

Can you make similar changes in other translated pages too other than english like (es,fr etc)

**Comment by sahajamit** [comment]
@Harsha509 : I done done these changes.

**Review by harsha509 — APPROVED** [review]
Thank you @sahajamit !

**Comment by harsha509** [comment]
Congratulations on your first contribution @sahajamit  🎉 🎉 🎉 🎉 🎉

**Pull request merged**
