### PR TITLE
Fix typo in design_strategies.en.md

### PR DESCRIPTION
**Pull request by geokats7**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Just a minor typo fix
### Motivation and Context
Documentation improvement
### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by luisfcorreia — DISMISSED** [review]
looks good, thanks

**Review by harsha509 — APPROVED** [review]
Thank you @geokats7 !

**Comment by harsha509** [comment]
Hi @geokats7 ,

Could you please Sign CLA to get this merged!

**Comment by harsha509** [comment]
Congratulations on your first contribution to Selenium docs @geokats7 🎉 🎉 🎉 !

**Pull request merged**
