### PR TITLE
Add Ruby sample code for chrome devtools

### PR DESCRIPTION
**Pull request by RustyNail**
Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Add Ruby sample code for chrome devtools.
The change has been applied to all translation files.
It has been verified that the added code works.

### Motivation and Context
I think it will be very useful for those who will learn from now on to put the sample code on this page.
This time, I added the code of Ruby, which is the programming I use every day.
I hope my activities are useful.

### Types of changes
- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist
- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

The screenshot I checked using hugo are attached below. 
screenshot

### CODE REVIEW

**Comment by RustyNail** [comment]
@raju249 

Nice to meet you.
Could you please review my pull request?
I asked you because I saw a review with a corresponding pull request ( https://github.com/SeleniumHQ/seleniumhq.github.io/pull/623 )similar to this pull request.

**Comment by raju249** [comment]
Thanks for the mention @RustyNail 

I would like to ask for help from @p0deje as he has the context around in the ruby binding.

Thanks 🙏 🙇‍♂️

**Comment by RustyNail** [comment]
@raju249 @JS31096 
Thank you so much.

**Review by p0deje — DISMISSED** [review]
I'd recommend using plain symbols for hash keys, but other than that - it all makes perfect sense. Thank you!

```ruby
coordinates = { latitude: 35.689487,
                longitude: 139.691706,
                 accuracy: 100 }
```

**Comment by RustyNail** [comment]
@p0deje 
Thank you for your review.

The content pointed out has been corrected.
Please check again.

**Review by p0deje — APPROVED** [review]
LGTM

**Review by harsha509 — APPROVED** [review]
Thank you @RustyNail !

Thank you for reviewing the PR @p0deje !

**Pull request merged**
