### PR TITLE
Fix for #654 : https://github.com/SeleniumHQ/seleniumhq.github.io/issues/654

### LINKED ISSUE #654: Was confused after reading: https://www.selenium.dev/documentation/en/webdriver/page_loading_strategy/
Was confused after reading: https://www.selenium.dev/documentation/en/webdriver/page_loading_strategy/

"This will make Selenium WebDriver to wait until the initial HTML document has been completely loaded and parsed, and discards loading of stylesheets, images and subframes." 

Are you saying that they are loaded, just not processed?

_Originally posted by @githubuser100007 in https://github.com/SeleniumHQ/selenium/issues/9315#issuecomment-808208834_

### PR DESCRIPTION
**Pull request by jags14385**
Fixed #654  

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by diemol — CHANGES_REQUESTED** [review]
Can you please make this change in the other pages?
https://www.selenium.dev/documentation/about/style/#translations

**Review by diemol — CHANGES_REQUESTED** [review]
Two pages are still missing the content, would you like to continue working on this PR?

**Review by diemol — APPROVED** [review]
Thank you

**Comment by jags14385** [comment]
@diemol sorry got busy. Had to travel.

**Pull request merged**
