### PR TITLE
Provide Mocha install instructions to run first JS script

### LINKED ISSUE #1160: [JS]: Missing documentation on running the firstscript.spec.js
### What happened?

I'm not able to run Slenium with Javascript. I try to start my tes.js an dthere is this error

### How can we reproduce the issue?

```shell
I don't know
test.js
```

### Relevant log output

```shell
$ node test.js
[INFO] Searching for WebDriver executables installed on the current system...
[INFO] ... located firefox
[INFO] Running tests against [firefox]
C:\Users\nbirken\Documents\Selenium\js\node_modules\selenium-webdriver\testing\index.js:229
  after(function () {
  ^

ReferenceError: after is not defined
    at init (C:\Users\nbirken\Documents\Selenium\js\node_modules\selenium-webdriver\testing\index.js:229:3)
    at suite (C:\Users\nbirken\Documents\Selenium\js\node_modules\selenium-webdriver\testing\index.js:374:5)
    at Object.<anonymous> (C:\Users\nbirken\Documents\Selenium\js\test.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

### Operating System

Windows 10

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Firefox

### What are the browser driver(s) and version(s) where you see this issue?

Firefox

### Are you using Selenium Grid?

_No response_

### PR DESCRIPTION
**Pull request by dublinsubway**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description
Add a line explaining the way to run their script as it might not be clear for beginners. Closes #1160.

### Motivation and Context
Providing people with a bit more detailed information about the way they can run their first test script locally.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [X] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [X] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [X] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by titusfortner — DISMISSED** [review]
First, thanks for this PR.

The goal of the "first script" page is to try to demonstrate the minimum necessary for executing Selenium code. I think the right answer here is to create a new page in Getting Started Section for "Scaling Selenium" or "Test Runners" or something. Let's discuss in #documentation channel and see where we want to take this.

**Comment by diemol** [comment]
What was the conclusion of the discussion?

**Comment by harsha509** [comment]
I have created a section for `Test Runners` in here https://www.selenium.dev/documentation/webdriver/getting_started/first_script/#test-runners

But needs a decision on this too!

**Comment by diemol** [comment]
That section probably makes sense, but I would leave it in a different page and link it from the `First Script` page, as it is now, it can confuse more than clarify.

**Comment by titusfortner** [comment]
I think what we want to do is to create a separate `test_runners.md` docs file where we discuss why you would use a test runner, list the various options in each language, and then show code for the ones we're using in `examples/`

**Comment by harsha509** [comment]
Thank you for the PR @dublinsubway !

It appears that the documentation has already been updated with instructions on how to run tests using Mocha.
Closing this PR considering it's already resolved.

**Pull request closed without merging**
