### PR TITLE
Missing closing parentheses

### PR DESCRIPTION
**Pull request by TDroogers**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

A closing parentheses was missing in the documentation, resulting in a build error.

### Motivation and Context

It is annoying.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)
- [x] Fixed typo

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @TDroogers ,

Thank you for raising the PR.

Can you add similar changes in translated pages which are other than in English!

**Comment by TDroogers** [comment]
Sure

**Review by harsha509 — APPROVED** [review]
Thank you @TDroogers !

**Comment by harsha509** [comment]
Congratulations on your first contribution to selenium docs @TDroogers 🎉 🎉 🎉 !

**Pull request merged**
