### PR TITLE
Update _index.pt-br.md

### PR DESCRIPTION
**Pull request by jaofrod**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @devjaof ,

Thank you for the PR.

Could you please sign the CLA and checklist to get this merged!

**Review by luisfcorreia — CHANGES_REQUESTED** [review]
Please check your spelling, there are some errors

**Comment by ushimachhabra** [comment]
hiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii

**Comment by harsha509** [comment]
Hi @devjaof ,

Hope you're doing well!

Did you get a change to look into above comments ?

**Comment by diemol** [comment]
This PR is not valid anymore because this page was translated.

**Pull request closed without merging**
