### PR TITLE
create example code file element interaction

### PR DESCRIPTION
**Pull request by rpallavisharma**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

create element interaction java file
### Description

created example code file
### Motivation and Context

to create complete executable code examples
### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by harsha509** [comment]
Hi @pallavigitwork ,

I'm a little puzzled. This pull request appears to have no modifications. Could you kindly inform me if there was anything overlooked in the commit?

Thanks,
Sri

**Comment by rpallavisharma** [comment]
Hi @harsha509 , i added a java file in the example folder - examples\java\src\test\java\dev\selenium\elements\interactions . let me know if you see it?

**Comment by diemol** [comment]
@pallavigitwork, why don't you refresh your fork and create a new PR to add the file again? There are no changes in this PR.

**Comment by rpallavisharma** [comment]
Hi @diemol , i created another PR https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1459, which @harsha509 has merged. i will close this.

**Comment by rpallavisharma** [comment]
duplicate

**Pull request closed without merging**
