### PR TITLE
Add Kotlin codes for using Chrome driver

### PR DESCRIPTION
**Pull request by kwongiho**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

 * add to use Driver for Kotlin

### Motivation and Context

 * I added an example code for Kotlin developers who first started using Selenium.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by jungjoon-yoon — DISMISSED** [review]
LGTM

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @kwongiho,

Thank you for raising the PR.

Could you please do the same changes in `.ja` doc too?

Thanks,
Harsha

**Comment by kwongiho** [comment]
Hi @harsha509 

I added codes for ja version
I also added java codes on ja version cos there's no example for Chrome driver using java

Thanks,
Kwongiho

**Review by harsha509 — CHANGES_REQUESTED** [review]
Could you please sign CLA to get this merged!

**Comment by kwongiho** [comment]
@harsha509 
I just signed!

Thanks :)

**Review by harsha509 — APPROVED** [review]
Thank you @kwongiho!

**Comment by harsha509** [comment]
Congratulations on your first contribution to Selenium Docs @kwongiho 🎉 🎉 !

**Pull request merged**
