### PR TITLE
Add build and release info to selenium-manager docs

### PR DESCRIPTION
**Pull request by bsquizz**
### Description
Provides more information about where the selenium-manager source code is located, how the binary is built, and how the pre-compiled binary gets included in releases via bazel build steps.

### Motivation and Context
Clearer understanding of the details of the build and release process.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by titusfortner** [comment]
Great! can you also copy/paste this (in English) at the bottom of the other 3 language files?
Thanks for contributing.

**Comment by titusfortner** [comment]
and it may already be out of date since I think Simon has a PR for tests to use a locally compiled version rather than pre-compiled binaries.

**Comment by titusfortner** [comment]
oh, forgot to deploy site. next PR...

**Comment by harsha509** [comment]
Done with an empty commit 😄

**Pull request merged**
