### PR TITLE
Add: Added kotlin sample code for keyUp action

### PR DESCRIPTION
**Pull request by Harsha509**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by Harsha509** [comment]
hi @diemol , i would like to know what is the targeted browser for testing sample codes. Initially i remember that we're targeting Firefox. Please let me know, it will be helpful from next PRs.

Thanks!

**Comment by diemol** [comment]
@Harsha509 I'd say Firefox or Chrome are fine.

**Comment by Harsha509** [comment]
Hi @diemol ,

Any reason this is not merged ? is there any changes required in this PR ?

**Comment by diemol** [comment]
Well, I have a day job and a family, sometimes I cannot reply as fast as I would like, apologies for the delay.

**Comment by Harsha509** [comment]
Got it. Apologies from my side too. Thanks for reviewing @diemol

**Pull request merged**
