### PR TITLE
Blog | Scaling Selenium Grid in Kubernetes using KEDA

### PR DESCRIPTION
**Pull request by Wolfe1**
### Description
Blog post on how selenium grid can scale in k8s using KEDA

Adaptation of https://www.linkedin.com/pulse/scaling-kubernetes-selenium-grid-keda-brandon-wolfe

### Motivation and Context
Help users avoid issues scaling their own grid instances in k8s

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by Wolfe1** [comment]
@diemol Is there anything else I need to do to get the additional checks run and reviewed?

**Comment by diemol** [comment]
@Wolfe1 not so far. Sorry, I was reviewing some days ago and I got distracted. I will review again between today and tomorrow.

**Comment by Wolfe1** [comment]
Made a small update to properly reference the latest documentation versions and set the minimum version of keda at 2.8.0.

**Comment by diemol** [comment]
Apologies again for the delay on this. Reviewing now and sharing it in social media afterwards.

**Review by diemol — APPROVED** [review]
Thank you, @Wolfe1!

**Pull request merged**
