### PR TITLE
Added python code to Arguments section

### PR DESCRIPTION
**Pull request by bhgr216**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

Added python code sample to the arguments section

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [X] Code example added (I have not added it to the translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by diemol — CHANGES_REQUESTED** [review]
Could you please add this to the other pages? `firefox.*.md`

**Comment by bhgr216** [comment]
Done.

**Review by diemol — CHANGES_REQUESTED** [review]
Did you see that it does not render correctly?
image
https://deploy-preview-1184--jovial-austin-42fe02.netlify.app/documentation/webdriver/browsers/firefox/

**Comment by bhgr216** [comment]
Sorry for the absolute mess - should be fixed now.

**Review by diemol — APPROVED** [review]
Thank you, @TurboSlayer!

**Pull request merged**
