### PR TITLE
Pin Python dependencies in requirements.txt

### PR DESCRIPTION
**Pull request by yvsvarma**
### Summary
- Pinned the following Python dependencies in `requirements.txt`:
  - pytest==8.3.4
  - trio==0.27.0
  - pytest-trio==0.8.0
  - pytest-rerunfailures==14.0
  - flake8==7.1.1
  - requests==2.32.3

### Justification
- Ensures consistent behavior across environments.
- Prevents unexpected issues from dependency updates or breaking changes.
- Improves reproducibility and maintainability.

### Verification
- Verified with `pytest`:
  - 137 passed, 16 skipped (platform-specific).

___

### **PR Type**
Enhancement

___

### **Description**
- Added version pinning for all Python dependencies in requirements.txt to ensure consistent behavior:
  - Testing: `pytest==8.3.4`, `pytest-trio==0.8.0`, `pytest-rerunfailures==15.0`
  - Development: `flake8==7.1.1`
  - Core dependencies: `trio==0.27.0`, `requests==2.32.3`
- Improves reproducibility by preventing unexpected updates or breaking changes
- Verified compatibility with existing test suite (137 passing tests)

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>requirements.txt</strong><dd><code>Pin Python test and development dependencies</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

examples/python/requirements.txt

<li>Pinned specific versions for 6 Python dependencies:<br>   - pytest <br>(7.3.0), trio (0.22.0), pytest-trio (0.8.0)<br>   - pytest-rerunfailures <br>(10.2), flake8 (6.1.0), requests (2.32.3)<br> <li> Replaced unpinned dependencies with exact versions<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/2110/files#diff-c233c301c314607d2dfcee9a9ec0d5a7b78a67d2c8927808fd4c9d382bbb4a8e">+6/-6</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by VietND96** [comment]
It looks like `pytest-rerunfailures==14.0` will be fine for CI using py3.8

```
ERROR: Ignored the following versions that require a different python version: 0.28.0 Requires-Python >=3.9; 15.0 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement pytest-rerunfailures==15.0 (from versions: 0.3, 0.5, 1.0.0, 1.0.1, 1.0.2, 2.0.0, 2.0.1, 2.1.0, 2.2, 3.0, 3.1, 4.0, 4.1, 4.2, 5.0, 6.0, 7.0, 8.0, 9.0, 9.1, 9.1.1, 10.0, 10.1, 10.2, 10.3, 11.0, 11.1, 11.1.1, 11.1.2, 12.0, 13.0, 14.0)
ERROR: No matching distribution found for pytest-rerunfailures==15.0
```

**Comment by yvsvarma** [comment]
Hi @VietND96 , Thank you for pointing this out! I have updated the dependency to use pytest-rerunfailures==14.0, which is compatible with Python 3.8 and suitable for the CI environment. Please let me know if any additional changes are required. Thanks again for your feedback!

**Comment by VietND96** [comment]
Thank you @yvsvarma! I merged your PR
2 CI failed on macOS runners are not related to this change.

**Comment by yvsvarma** [comment]
> Thank you @yvsvarma! I merged your PR 2 CI failed on macOS runners are not related to this change.

Thank you @VietND96, for your time and efforts in reviewing this! 🙏🏻

**Pull request merged**
