### PR TITLE
Update on_test_automation.en.md

### PR DESCRIPTION
**Pull request by sidsiddiqi**
A very small yet obvious grammatical fix to a sentence on this page.

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [x] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by boris779** [comment]
Can I also do the missing changes? I checked out the patch-1 branch from @sidsiddiqi 
How can I commit to this PR?

**Comment by Harsha509** [comment]
Hi @boris779,

This is a trivial change. We may need to give some more time for the author for the requested changes.

Thanks,
Harsha

**Comment by boris779** [comment]
I've compared the files, also the other languages (for on_test_automation.xx.md) are a kind of outdated, I already changed it. Give me a call if you want to merge that.

**Comment by Harsha509** [comment]
Yes @boris779 , You can create a PR referencing this PR and giving credits to the original author.
This will do i think.

Thanks,
Harsha

**Comment by boris779** [comment]
Raised a PR #178 which was forked from @sidsiddiqi

**Comment by diemol** [comment]
Replaced by #178, thanks @boris779

**Pull request closed without merging**
