### PR TITLE
adding select by visible text test in example

### PR DESCRIPTION
**Pull request by rpallavisharma**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

adding select by visible text test java file in example
### Motivation and Context

selenium documentation is changing.  adding code for select by visible text in example
### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by diemol — COMMENTED** [review]
Is there something missing? I do not see anything special in the changeset.

**Comment by rpallavisharma** [comment]
> changeset

I added a code for select list in the examples folder, for java

**Comment by diemol** [comment]
Strange, when I check the changed files on https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1136/files I only see 
image

**Comment by rpallavisharma** [comment]
> Strange, when I check the changed files on https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1136/files I only see image

I didn't modify any document. I added code in the example directory of java

**Review by diemol — APPROVED** [review]
Thank you, @pallavigitwork!

**Pull request merged**
