### PR TITLE
Added missing value for --detect-drivers param

### PR DESCRIPTION
**Pull request by mookkiah**
### Description

Documentation missing value for parameter `--detect-drivers` when used.  

```shell
 % java -jar selenium-server.jar node --detect-drivers
Expected a value after parameter --detect-drivers
Usage: node [options]
  Options:
    --allow-cors
      Whether the Selenium server should allow web browser connections from 
      any host
      Default: false
    --bind-bus
      Whether the connection string should be bound or connected. When true, 
      the component will be bound to the Event Bus (as in the Event Bus will 
      also be started by the component, typically by the Distributor and the 
      Hub). When false, the component will connect to the Event Bus.
    --config
      Config file to read from (may be specified more than once)
    --config-help
      Output detailed information about config options
      Default: false
    --detect-drivers
      Autodetect which drivers are available on the current system, and add 
      them to the Node.
      Default: true
    --docker, -D
      Docker configs which map image name to stereotype capabilities (example 
      `-D selenium/standalone-firefox:latest '{"browserName": "firefox"}')
    --docker-assets-path
      Absolute path where assets will be stored
    --docker-host
      Host name where the docker daemon is running
    --docker-port
      Port where the docker daemon is running
    --docker-url
      URL for connecting to the docker daemon
    --docker-video-image
      Docker image to be used when video recording is enabled
      Default: selenium/video:latest
    --driver-configuration
      List of configured drivers a Node supports. It is recommended to provide 
      this type of configuration through a toml config file to improve 
      readability. Command line example: --drivers-configuration name="Firefox 
      Nightly" max-sessions=2 stereotype='{"browserName": "firefox", 
      "browserVersion": "86", "moz:firefoxOptions": 
      {"binary":"/Applications/Firefox 
      Nightly.app/Contents/MacOS/firefox-bin"}}' 
    --driver-factory
      Mapping of fully qualified class name to a browser configuration that 
      this matches against. --driver-factory 
      org.openqa.selenium.example.LynxDriverFactory '{"browserName": "lynx"}'
    -I, --driver-implementation
      Drivers that should be checked. If specified, will skip 
      autoconfiguration. Example: -I "firefox" -I "chrome"
      Default: []
    --events-implementation
      Full classname of non-default event bus implementation
    --grid-url
      Public URL of the Grid as a whole (typically the address of the Hub or 
      the Router)
    --heartbeat-period
      How often, in seconds, will the Node send heartbeat events to the 
      Distributor to inform it that the Node is up.
      Default: 60
    --host
      Server IP or hostname: usually determined automatically.
    --https-certificate
      Server certificate for https. Get more detailed information by running 
      "java -jar selenium-server.jar info security"
    --https-private-key
      Private key for https. Get more detailed information by running "java 
      -jar selenium-server.jar info security"
    --log-encoding
      Log encoding
    --log-level
      Log level. Default logging level is INFO. Log levels are described here 
      https://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html 
      Default: INFO
    --max-sessions
      Maximum number of concurrent sessions. Default value is the number of 
      available processors.
      Default: 8
    --max-threads
      Maximum number of listener threads. Default value is: (available 
      processors) * 3.
      Default: 24
    --plain-logs
      Use plain log lines
      Default: true
    -p, --port
      Port to listen on. There is no default as this parameter is used by 
      different components, for example Router/Hub/Standalone will use 4444 
      and Node will use 5555.
    --publish-events
      Connection string for publishing events to the event bus
    --register-cycle
      How often, in seconds, the Node will try to register itself for the 
      first time to the Distributor.
      Default: 10
    --register-period
      How long, in seconds, will the Node try to register to the Distributor 
      for the first time. After this period is completed, the Node will not 
      attempt to register again.
      Default: 120
    --registration-secret
      Node registration secret
    --session-timeout
      Let X be the session-timeout in seconds. The Node will automatically 
      kill a session that has not had any activity in the last X seconds. This 
      will release the slot for other tests.
      Default: 300
    --structured-logs
      Use structured logs
      Default: false
    --subscribe-events
      Connection string for subscribing to events from the event bus
    --version
      Displays the version and exits.
      Default: false

```

### Motivation and Context
This change make the command pass as is in the documentation

### Types of changes

- [ x] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

image

### CODE REVIEW

**Comment by mookkiah** [comment]
https://seleniumhq.slack.com/archives/C0ABCS03F/p1618050855344800

**Comment by harsha509** [comment]
Hi @mookkiah ,

Thanks for the PR.

This PR contains a file that is not related to this PR. 
`site_source_files/content/blog/2021/public-project-meeting-20210408.md`

Can you remove it ?

**Review by harsha509 — CHANGES_REQUESTED** [review]
Can you remove this file ?

`site_source_files/content/blog/2021/public-project-meeting-20210408.md` from this PR

**Comment by mookkiah** [comment]
I don't see the file you are referring. I scrolled through this page 3 times and did a search "meeting"- https://github.com/SeleniumHQ/seleniumhq.github.io/pull/662/files

Please help me finding out

**Comment by mookkiah** [comment]
image

**Review by harsha509 — APPROVED** [review]
Thank you @mookkiah !

**Pull request merged**
