### PR TITLE
grammar mistake: react -> React

### PR DESCRIPTION
**Pull request by TS000**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Grammar mistake. React is capitalized.

### Motivation and Context
Grammar is important.

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [x ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @TS000 ,

Thanks for the PR. 

Can you please make changes in other translated pages too (like es,de, nl...) within the same PR.

Thanks,
Harsha

**Comment by TS000** [comment]
Yes, would you like me to make the changes across all languages in one PR?

**Comment by harsha509** [comment]
> Yes, would you like me to make the changes across all languages in one PR?

Yes!

**Comment by harsha509** [comment]
Replaced with PR https://github.com/SeleniumHQ/seleniumhq.github.io/pull/518 by same author!

**Pull request closed without merging**
