### PR TITLE
typo in Maximise

### PR DESCRIPTION
**Pull request by sir-Gee**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [x] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @sir-Gee ,

Thanks for the PR.

1. Can you please make the same changes to other translated pages , which are not in english (es, de, zh-cn)
2. Can you please complete the Checklist and sign the CLA

Thank you!

**Comment by harsha509** [comment]
Hi @sir-Gee ,

Did you get a chance to look into the above comments ?

**Comment by sir-Gee** [comment]
Hi @JS31096 ,
I have read the comments you left. I have signed CLA, but i am not sure about downloading Hugo just to correct a typo. If downloading hugo is a must, so you can close my pull request.

**Comment by diemol** [comment]
For typos it is not needed, we have an automatic deployment with netlify so it can be checked.
We are just asking to correct the typos on the other pages as well. 🙏

**Comment by harsha509** [comment]
Hi @sir-Gee,

Thank for the PR. As the PR went stale i have replaced the typo with new commit.

**Pull request closed without merging**
