### PR TITLE
Edit English translations

### PR DESCRIPTION
**Pull request by Michael4d45**
### Description

I've made some grammatical edits to the documentation for English translations. 

### Motivation and Context

This provides better readability. 

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [x] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @Michael4d45 ,

Thanks for the PR.
Could you please do the same changes in other translated pages which are in English.

Thanks,
Harsha

**Comment by harsha509** [comment]
Hi @Michael4d45 ,

Did you get a chance to look into above comments!

**Comment by Michael4d45** [comment]
> Could you please do the same changes in other translated pages which are in English.

Yeah, I can do that.

**Review by harsha509 — APPROVED** [review]
LGTM !

**Pull request merged**
