### PR TITLE
add a csharp description:SelectElement code Demo for each language

### PR DESCRIPTION
**Pull request by coodjokergl**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by coodjokergl** [comment]
> Thank you @coodjokergl !
> 
> Also, I'd like to request you to provide a single PR going further for similar type of changes.
> 
> Regards,
> Harsha

does it mean : i should commit this changes with one page file for  each?

**Comment by Harsha509** [comment]
> > Thank you @coodjokergl !
> > Also, I'd like to request you to provide a single PR going further for similar type of changes.
> > Regards,
> > Harsha
> 
> does it mean : i should commit this changes with one page file for each?

not exactly, A single PR (one commit) with changes in all files :)

**Comment by coodjokergl** [comment]
> > > Thank you @coodjokergl !
> > > Also, I'd like to request you to provide a single PR going further for similar type of changes.
> > > Regards,
> > > Harsha
> > 
> > 
> > does it mean : i should commit this changes with one page file for each?
> 
> not exactly, A single PR (one commit) with changes in all files :)

get it! it's my mistake,how to fix this commit problem? my commits already merge to the master

**Comment by Harsha509** [comment]
> > > > Thank you @coodjokergl !
> > > > Also, I'd like to request you to provide a single PR going further for similar type of changes.
> > > > Regards,
> > > > Harsha
> > > 
> > > 
> > > does it mean : i should commit this changes with one page file for each?
> > 
> > 
> > not exactly, A single PR (one commit) with changes in all files :)
> 
> get it! it's my mistake,how to fix this commit problem? my commits already merge to the master

No Issues, I've merged it for now. You can follow the process for new PR's

**Pull request merged**
