### PR TITLE
moved python examples for Relative Locators

### PR DESCRIPTION
**Pull request by shbenzer**
### **User description**
moved python examples for relative locators

### Description
moved python examples for relative locators in all languages

### Motivation and Context
increase comprehensiveness of website

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

___

### **PR Type**
enhancement, documentation

___

### **Description**
- Added Python test examples demonstrating the use of relative locators in Selenium.
- Updated documentation in multiple languages (English, Japanese, Portuguese, Chinese) to include links to the new Python test examples.
- Enhanced the comprehensiveness of the website by integrating Python examples directly into the documentation using `gh-codeblock`.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>test_locators.py</strong><dd><code>Add Python tests for relative locators demonstration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

examples/python/tests/elements/test_locators.py

<li>Added multiple test functions demonstrating relative locators.<br> <li> Utilized <code>locate_with</code> for different relative positions like above, <br>below, near, etc.<br> <li> Each test function opens a web page and interacts with elements using <br>relative locators.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1962/files#diff-37a84073184f55bf24b44b3a435c07704ca453e3d74fac87370df04efec76cb8">+52/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>locators.en.md</strong><dd><code>Update English documentation with Python example links</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/elements/locators.en.md

<li>Updated Python code examples to use <code>gh-codeblock</code> for better <br>integration.<br> <li> Enhanced documentation with direct references to Python test file <br>lines.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1962/files#diff-bad5c08d78f84e8bd7528d1a2a3181973375147d3f8bc5b9678cfce7dbe76aab">+13/-13</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>locators.ja.md</strong><dd><code>Update Japanese documentation with Python example links</code>&nbsp; &nbsp; </dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/elements/locators.ja.md

<li>Updated Python code examples to use <code>gh-codeblock</code>.<br> <li> Improved documentation with direct references to Python test file <br>lines.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1962/files#diff-06ad92a757672227e965b2d837608b89da6bb02315528815d9e6fa2eac9114af">+18/-13</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>locators.pt-br.md</strong><dd><code>Update Portuguese documentation with Python example links</code></dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/elements/locators.pt-br.md

<li>Updated Python code examples to use <code>gh-codeblock</code>.<br> <li> Enhanced documentation with direct references to Python test file <br>lines.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1962/files#diff-d1f5d96e2cf4217d2473ebd28f060129cedf8bde199fc884493ffd01d205d994">+18/-13</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>locators.zh-cn.md</strong><dd><code>Update Chinese documentation with Python example links</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/elements/locators.zh-cn.md

<li>Updated Python code examples to use <code>gh-codeblock</code>.<br> <li> Improved documentation with direct references to Python test file <br>lines.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1962/files#diff-275209ad35c57329488099cdbd775ba45e6386d21561836642e99c0b67721f10">+18/-13</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by pmartinez1** [comment]
Kind of a dup of https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1903/files?

**Comment by shbenzer** [comment]
> Kind of a dup of https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1903/files?

I honestly forgot yours included relative locators - I'll close my pr.

**Comment by pmartinez1** [comment]
> > Kind of a dup of https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1903/files?
> 
> 
> 
> I honestly forgot yours included relative locators - I'll close my pr.

I'm trying to help out by updating/moving python as much of the python docs. Would it be useful for me to create an "issue" so others are aware/to avoid dups?

**Comment by shbenzer** [comment]
> I'm trying to help out by updating/moving python as much of the python docs. Would it be useful for me to create an "issue" so others are aware/to avoid dups?

That's great! 

I don't think creating an issue is necessary though, duplicates are rather rare (though granted I did just do it lol). But you could put a message in the selenium-documentation slack about what you're doing to give people a heads-up and let us know when you've put out a new pr.

**Pull request closed without merging**
