### PR TITLE
describe element actions

### PR DESCRIPTION
**Pull request by titusfortner**
Moves some of the non-Actions API commands out of Actions API pages and creates a page for describing the 5 basic element actions.

Most of this content is just moved from one place to another.

Also added "Coming Soon" comments for things that need to get added.

### CODE REVIEW

**Review by diemol — CHANGES_REQUESTED** [review]
This is a good idea, however I would remove the "coming soon" comments. I would prefer to create issues for that.

**Comment by titusfortner** [comment]
There's more code that needs to be added, and the wheel files are straight placeholders until after Selenium 4.2 is released, but the content for all of this has been overhauled as well.

**Comment by titusfortner** [comment]
I tweaked the alert messages for code & content to allow both generic and specific usage
Replaced all the "coming soon" with alerts requesting help

**Comment by diemol** [comment]
Merged as part of #920

**Pull request closed without merging**
