### PR TITLE
feat: translate webDriver and support features into Portuguese

### PR DESCRIPTION
**Pull request by Afranioalves**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

translated into Portuguese the pages related to `support features`, `using selenium` and `webdriver`, updating their pt-br.md files

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

@aosccode

### CODE REVIEW

**Comment by sombo20** [comment]
@shs96c 
@cjayswal 
@connerT

**Comment by sombo20** [comment]
@luisfcorreia

**Comment by diemol** [comment]
For future PRs, please make them smaller (avoid changing too many files). Thanks!

**Review by luisfcorreia — APPROVED** [review]
thanks for contributing, text looks OK

**Comment by sombo20** [comment]
@luisfcorreia tks, waiting to merge!

**Comment by sombo20** [comment]
@diemol hhahaha,okay .

**Comment by Afranioalves** [comment]
777- @aosccode look this

**Pull request merged**
