### PR TITLE
#1697 - Fixed Hugo depericate warning on custom params

### PR DESCRIPTION
**Pull request by chamiz**
## **User description**
Fixed Hugo depericate warning "custom params on the language top level was deprecated in Hugo v0.112.0 and will be removed in Hugo 0.126.0"

Fix for https://github.com/SeleniumHQ/seleniumhq.github.io/issues/1697

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description
After updating hugo v0.125.4 , I'm getting "custom params on the language top level was deprecated in Hugo v0.112.0 and will be removed in Hugo 0.126.0"for several translations.

### Motivation and Context
So as a fix, we need to put the values as suggested.
[languages.zh-cn.params]

Source
https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120

### Types of changes

- [X ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ X] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [X] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ X] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

___

## **Type**
Enhancement

___

## **Description**
- Updated `hugo.toml` to move language-specific 'description' fields into a new 'params' sub-table for each language.
- This modification is in response to deprecation warnings from Hugo, ensuring compatibility with future Hugo versions.
- Affected languages include English, Portuguese (Brazilian), Simplified Chinese, Japanese, and an unspecified 'Other' language.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>hugo.toml</strong><dd><code>Update Language Configurations to New Hugo Params Structure</code></dd></summary>
<hr>
      
website_and_docs/hugo.toml

<li>Moved 'description' for each language into a new 'params' sub-table to <br>adhere to Hugo's updated requirements.<br> <li> This change affects multiple language configurations including <br>English, Portuguese (Brazilian), Simplified Chinese, Japanese, and <br>Other.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1699/files#diff-7c7b0a30aca04da823c578a790ae39208bfb7bc0195ccc764f74a3f2a049e467">+11/-6</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by diemol — CHANGES_REQUESTED** [review]
Thank you for this, @chamiz!

Could you please help us update the version as well? I found a few places, there might be more:
- https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/README.md?plain=1#L14
- https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/netlify.toml
-  https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/.github/workflows/deploy.yml
- https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/.github/workflows/test.yml

**Comment by chamiz** [comment]
Thanks for reviewing. I will do those changes as well.

**Comment by chamiz** [comment]
@diemol Ready to merge.

**Comment by diemol** [comment]
It seems the build is now failing.

**Comment by chamiz** [comment]
yes. "no such template "_internal/google_analytics_async.html" Error. 
It was deprecated. They already changed the Docsy repo but haven't released the version with the fix yet.

Also my bad, I forgot that I made that change locally. :) 

Until they make the release I will set the Hugo version to 0.124.1. 

image

**Comment by chamiz** [comment]
https://github.com/google/docsy/discussions/1985#discussioncomment-9289521

Docsy maintainers team bumped the version to 0.10.0 which has fix for "no such template "_internal/google_analytics_async.html" Error.

**Comment by diemol** [comment]
The branch name you have `#1697-Hugo-depericate-warning-custom-params-on-the-language-top-level` is erroring the deploy script. I guess we did not consider to escape especial characters. 

Could you change the branch name so we can see the deployment, please?

**Comment by chamiz** [comment]
Hi @diemol ,
Created a new PR with the renamed branch.
https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1702

I closed this one

**Pull request closed without merging**
