### PR TITLE
typo issue

### PR DESCRIPTION
**Pull request by as842718**
We are missing '1' in 'Note 1 :'

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [x] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by Harsha509** [comment]
HI @as842718,

Good one. Can you also please update the changes to other translated pages. Also signing the CLA and completing above checklist.

Thanks,
Harsha

**Comment by as842718** [comment]
> HI @as842718,
> 
> Good one. Can you also please update the changes to other translated pages. Also signing the CLA and completing above checklist.
> 
> Thanks,
> Harsha

Please review and accept my pull request

**Comment by Harsha509** [comment]
Hi as842718,

Thanks for the PR.

I think this PR has gone stale. I've added the above change in PR https://github.com/SeleniumHQ/seleniumhq.github.io/pull/155

Thanks,
Harsha

**Comment by diemol** [comment]
Replaced by #155 since we didn't get any reply from the OP

**Pull request closed without merging**
