### PR TITLE
missing tab in options.en.md

### PR DESCRIPTION
**Pull request by gulifeng8**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by titusfortner — APPROVED** [review]

**Review by diemol — APPROVED** [review]
Thank you!

**Review by diemol — CHANGES_REQUESTED** [review]
Can you also update it in the following places?

- https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/website_and_docs/content/documentation/webdriver/drivers/options.ja.md?plain=1#L431
- https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/website_and_docs/content/documentation/webdriver/drivers/options.pt-br.md?plain=1#L467
- https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/website_and_docs/content/documentation/webdriver/drivers/options.zh-cn.md?plain=1#L455

**Comment by harsha509** [comment]
Hi @gulifeng8 ,

Thank you for the PR. I have made similar changes in other translated pages referring your commit.

Thanks,
Sri Harsha

**Review by harsha509 — APPROVED** [review]

**Comment by harsha509** [comment]
Congratulations on your first contribution to selenium-docs @gulifeng8 :tada: :tada:

**Comment by gulifeng8** [comment]
Thanks for everyone's effort, sorry for off-line some days.

**Pull request merged**
