### PR TITLE
Add ruby examples for the using selenium page

### PR DESCRIPTION
**Pull request by aguspe**
### Description
Currently, the [using selenium](https://www.selenium.dev/documentation/webdriver/getting_started/using_selenium/) page is lacking examples in ruby and this PR aims to add those examples

Screenshot 2024-03-29 at 14 00 12

### Motivation and Context
This will help people starting with selenium and ruby to easily execute their first test and also provide a better overview through examples

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

___

## **Type**
enhancement, documentation

___

## **Description**
- Added instructions on how to execute a Ruby script in the Ruby examples README.
- Enhanced the Ruby Selenium test example with `before` and `after` hooks for better test setup and teardown.
- Fixed a broken link in the Selenium Manager documentation for English, Japanese, Brazilian Portuguese, and Chinese versions.
- Added Ruby examples in the documentation for running Selenium files and using Selenium, making it easier for Ruby developers to get started with Selenium.
- Updated the `fs-extra` package version in `package-lock.json` to 11.2.0.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>README.md</strong><dd><code>Add Ruby Script Execution Instructions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
examples/ruby/README.md

- Added instructions on how to execute a Ruby script.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1649/files#diff-8cda852ac6af50a08acfe9db1ee6cd7f307de973a3372a7d43535bec30eedf13">+9/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>using_selenium_spec.rb</strong><dd><code>Enhance Ruby Selenium Test Example</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
examples/ruby/spec/getting_started/using_selenium_spec.rb

<li>Updated the test to use <code>before</code> and <code>after</code> hooks for setup and teardown.<br> <li> Improved the test example by making it more comprehensive.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1649/files#diff-e0817e6554019401f3bf32012e3a7242a2d5f453cd896fa116d73fcd2667ba20">+15/-12</a>&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>selenium_manager.en.md</strong><dd><code>Fix Broken Link in Selenium Manager Documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
website_and_docs/content/documentation/selenium_manager.en.md

- Fixed a broken link in the Selenium Manager documentation.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1649/files#diff-abfd3399fa93ee23ed8a6b8637b566cf12c67d477fda705ed877a10f013047b7">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>first_script.en.md</strong><dd><code>Add Ruby Example for Running Selenium Files</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
website_and_docs/content/documentation/webdriver/getting_started/first_script.en.md

- Added Ruby example on how to run Selenium files.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1649/files#diff-0757312e3d52b8201ca35b35c4bdad191db3e0978681a45c0cad1bebeb49fd3c">+20/-3</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>using_selenium.en.md</strong><dd><code>Add Ruby Examples for Using Selenium</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
website_and_docs/content/documentation/webdriver/getting_started/using_selenium.en.md

<li>Added Ruby examples for setting up, tearing down, and running tests <br>with Selenium.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1649/files#diff-f521d4cd05fea84ac0fd18184a214f8ac2cd023a7f2c1a7e2b43495504b7b9f0">+11/-7</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Dependencies
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>package-lock.json</strong><dd><code>Update fs-extra Package Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
website_and_docs/package-lock.json

- Updated `fs-extra` package from version 11.1.0 to 11.2.0.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1649/files#diff-0c56697d4eaad8034e5c9d72023ffa5aba3bfa055302d6aa2bff981ddb99d375">+6/-6</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by aguspe** [comment]
@diemol I created this PR from https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1613, the biggest changes in the code happen in examples/ruby/spec/getting_started/using_selenium_spec.rb

I remove the spec helper to make the example self-contained, and to add examples for hooks

**Review by diemol — CHANGES_REQUESTED** [review]
Thank you, @aguspe!

The "Asserting" seems wrong. Could you please check it?

https://deploy-preview-1649--selenium-dev.netlify.app/documentation/webdriver/getting_started/using_selenium/#asserting

image

**Review by diemol — CHANGES_REQUESTED** [review]
@aguspe looks like the build fails due to the changes in the file, it is probably better to leave the `rspec_helper` in.

**Comment by aguspe** [comment]
> @aguspe looks like the build fails due to the changes in the file, it is probably better to leave the `rspec_helper` in.

Hi @diemol thank you so much for your review, I will give it a look today! 

Also Happy Easter!

**Comment by aguspe** [comment]
@diemol sorry for the delay, I have rolled back the spec helper removal but I have one question,

On the using selenium spec originally the test finished with driver.quit

However, on the spec helper we have in line` config.after { @driver&.quit }`

So if you execute the example normally, the example fails because the config.after trying to quit and already quit the driver, that's why I removed it also to keep the examples more cohesively, by having the hooks in one file

Right now, I deleted the after hook on the using selenium file and I'm using the config.after hook for the example.

However, I have two questions:

* Is it on purpose that the original selenium spec file fails if executed by itself?
* Do we want to assume that somebody starting to use Rspec and Selenium

This is the error that occurs when executing the using_selenium_spec.rb currently:

`Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:9515 (Connection refused - connect(2) for "127.0.0.1" port 9515)

  0) Using Selenium uses eight components
     Failure/Error: config.after { @driver&.quit }

     Errno::ECONNREFUSED:
       Failed to open TCP connection to 127.0.0.1:9515 (Connection refused - connect(2) for "127.0.0.1" port 9515)`
       
 Thank you so much for the help and the review! 
 
 After this PR is merged I will continue updating the docs for Ruby, also, just to know if it would be helpful, my mother tongue is Spanish, would it help if I add Spanish translations or would that give more work to other people maintaining the docs?

**Comment by aguspe** [comment]
Also @diemol, another question that might be a bit dumb, where can I see the Netlify deployment? it's okay if I don't have access I just wanna check that I'm not missing anything since I'm trying to follow the committer rules and to give you less work on the reviews

**Comment by diemol** [comment]
>On the using selenium spec originally the test finished with driver.quit

OK, so probably this was not being executed in CI. But now the idea is to show an example with a test runner, so I believe the changes make sense.

>Is it on purpose that the original selenium spec file fails if executed by itself?

The idea is to execute it with the test runner, which is the text shown before the complete code example.

>Do we want to assume that somebody starting to use Rspec and Selenium

We are not assuming that, we are simply showing that as a test runner. 

>Also @diemol, another question that might be a bit dumb, where can I see the Netlify deployment? it's okay if I don't have access I just wanna check that I'm not missing anything since I'm trying to follow the committer rules and to give you less work on the reviews

The deployment can be seen in a URL posted by Netlify above. However, you can always run this site locally and avoid waiting for the deployment (the deployment needs to be approved manually when it comes from a non-trusted repository).

>After this PR is merged I will continue updating the docs for Ruby, also, just to know if it would be helpful, my mother tongue is Spanish, would it help if I add Spanish translations or would that give more work to other people maintaining the docs?

Thank you for the offer. @titusfortner is exploring alternatives because it has proven to be extremely hard to maintain the documentation in different languages.

**Review by diemol — APPROVED** [review]

**Comment by aguspe** [comment]
> > On the using selenium spec originally the test finished with driver.quit
> 
> OK, so probably this was not being executed in CI. But now the idea is to show an example with a test runner, so I believe the changes make sense.
> 
> > Is it on purpose that the original selenium spec file fails if executed by itself?
> 
> The idea is to execute it with the test runner, which is the text shown before the complete code example.
> 
> > Do we want to assume that somebody starting to use Rspec and Selenium
> 
> We are not assuming that, we are simply showing that as a test runner.
> 
> > Also @diemol, another question that might be a bit dumb, where can I see the Netlify deployment? it's okay if I don't have access I just wanna check that I'm not missing anything since I'm trying to follow the committer rules and to give you less work on the reviews
> 
> The deployment can be seen in a URL posted by Netlify above. However, you can always run this site locally and avoid waiting for the deployment (the deployment needs to be approved manually when it comes from a non-trusted repository).
> 
> > After this PR is merged I will continue updating the docs for Ruby, also, just to know if it would be helpful, my mother tongue is Spanish, would it help if I add Spanish translations or would that give more work to other people maintaining the docs?
> 
> Thank you for the offer. @titusfortner is exploring alternatives because it has proven to be extremely hard to maintain the documentation in different languages.

Great thank you for the answers and the explanation!

Have a great weekend

**Pull request merged**
