### PR TITLE
Fix closing tag of Ordered List example

### PR DESCRIPTION
**Pull request by effeix**
The ordered list example under 'Locating multiple elements' is using `</ul>` as closing tag and should be using `</ol>`.

Before             |  After
:-------------------------:|:-------------------------:
Screen Shot 2021-01-05 at 10 56 08  |  Screen Shot 2021-01-05 at 10 55 28

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [x] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by diemol — CHANGES_REQUESTED** [review]
Could you please change this also on the other `locating_elements.*.md` files?

**Comment by effeix** [comment]
Sure! Working on it.

**Review by diemol — APPROVED** [review]
Thank you, @gustavoefeiche!

**Comment by effeix** [comment]
No problem! :D

**Pull request merged**
