### PR TITLE
typo: fix sentence fragment

### PR DESCRIPTION
**Pull request by yongchand**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

There was a sentence fragment in components part

### Motivation and Context

Looks very confusing for users. Let me know if it is not the router which receives the event.

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @yongchand,

Thanks for the PR. Could you please do the similar changes in other translated pages too!

**Comment by yongchand** [comment]
@harsha509 I have no knowledge in Chinese/Japanese/Portuguese.. I can open new issue for this though.
fyi. Seems like a document in Portuguese deleted this sentence @harsha509

**Comment by luisfcorreia** [comment]
Other languages may not have the same issue, for me, this change is acceptable

**Comment by harsha509** [comment]
Ah got it. 

Thought the change is required for translated pages too. If those are already translated we can ignore!

**Review by harsha509 — APPROVED** [review]
Thank you @yongchand !

**Pull request merged**
