### PR TITLE
Translate remaining pt-br docs

### PR DESCRIPTION
**Pull request by effeix**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [x] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by effeix** [comment]
Hi @diemol and @JS31096! Translated the remaining pages to pt-br (that were missing from my last PR). There are a lot of changes and I tried to review them all before submitting, let me know if I missed something! :)

**Comment by diemol** [comment]
@gustavoefeiche, thank you!

Sorry, we merged something earlier today that created a merge conflict here, would it be ok if you have a look a it?

**Comment by effeix** [comment]
Done! @diemol

**Comment by harsha509** [comment]
Deploy preview looks good!

**Review by harsha509 — APPROVED** [review]
Thank you @gustavoefeiche !

**Pull request merged**
