### PR TITLE
Fixing English grammar

### PR DESCRIPTION
**Pull request by Nisim761**
### **User description**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [x] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

___

### **PR Type**
Documentation

___

### **Description**
- Corrected a grammatical error in the "Assertions in Page Objects" section.
- Added a newline at the end of the file to adhere to best practices.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>page_object_models.en.md</strong><dd><code>Fix grammatical error and add newline in documentation</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

website_and_docs/content/documentation/test_practices/encouraged/page_object_models.en.md

<li>Corrected a grammatical error in the text.<br> <li> Added a newline at the end of the file.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1803/files#diff-cfc30f24cd0d69c4ac0bd17360cb46edb221a357b4e39c82851365bc931043ee">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @Nisim761 ,

Thank you for the PR.

To maintain consistency across all language versions, could you please replicate the changes you made on the main page to the other translated pages which are in english (pt-br, zh-cn, ja)?

Thanks,
Sri

**Comment by Nisim761** [comment]
> Hi @Nisim761 ,
> 
> Thank you for the PR.
> 
> To maintain consistency across all language versions, could you please replicate the changes you made on the main page to the other translated pages which are in English (pt-br, zh-cn, ja)?
> 
> Thanks, Sri

I am not really sure how. I only read the English version. I checked, couldn't find this error on other pages in English.

**Comment by harsha509** [comment]
> > Hi @Nisim761 ,
> > Thank you for the PR.
> > To maintain consistency across all language versions, could you please replicate the changes you made on the main page to the other translated pages which are in English (pt-br, zh-cn, ja)?
> > Thanks, Sri
> 
> I am not really sure how. I only read the English version. I checked, couldn't find this error on other pages in English.

No worries, i have updated other pages with commit https://github.com/SeleniumHQ/seleniumhq.github.io/commit/fa62b405393ba396d9579fef35630489e6fea533 referring to this PR!

**Review by harsha509 — APPROVED** [review]

**Comment by Nisim761** [comment]
> > > Hi @Nisim761 ,
> > > Thank you for the PR.
> > > To maintain consistency across all language versions, could you please replicate the changes you made on the main page to the other translated pages which are in English (pt-br, zh-cn, ja)?
> > > Thanks, Sri
> > 
> > 
> > I am not really sure how. I only read the English version. I checked, couldn't find this error on other pages in English.
> 
> No worries, i have updated other pages with commit [fa62b40](https://github.com/SeleniumHQ/seleniumhq.github.io/commit/fa62b405393ba396d9579fef35630489e6fea533) referring to this PR!

Thank you!

**Pull request merged**
