### PR TITLE
Adding initial version of Code of Conduct

### PR DESCRIPTION
**Pull request by diemol**
This PR adds an initial version of the Code of Conduct for the Selenium project.

### CODE REVIEW

**Comment by barancev** [comment]
Let's mention other official discussion spaces (IRC, Slack, what else?)

**Comment by diemol** [comment]
@barancev they are mentioned in #108

**Comment by diemol** [comment]
More specifically, here https://github.com/SeleniumHQ/seleniumhq.github.io/blob/governance-docs/GOVERNANCE.md#communication-channels

**Comment by barancev** [comment]
I mean the Scope section that reads:

"Examples of representing a project or community include using an official project e-mail address, posting via an official social media account, or acting as an appointed representative at an online or offline event"

I believe that answering in the email list or IRC are also examples of "representing"

**Comment by diemol** [comment]
Closing in favor of an ongoing draft

**Pull request closed without merging**
