### PR TITLE
Added console log Java test example.

### PR DESCRIPTION
**Pull request by connerT**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Added Java test, in all languages, for console log access in DevTools (Selenium 4)

### Motivation and Context
Needed a code example of this functionality

### Types of changes

-  [x] Code example added (and I also added the example to all translated languages)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by harsha509 — COMMENTED** [review]
Hi @connerT,

Thanks for the PR. Could you please sign the CLA to get this merged!

**Comment by connerT** [comment]
> Hi @connerT,
> 
> Thanks for the PR. Could you please sign the CLA to get this merged!

How do I sign the CLA?

**Comment by connerT** [comment]
> Hi @connerT,
> 
> Thanks for the PR. Could you please sign the CLA to get this merged!

Done. Thanks!

**Review by harsha509 — APPROVED** [review]
Thank you @connerT !

**Comment by harsha509** [comment]
Congratulations on your first contribution to Selenium docs @connerT 🎉  🎉  !

**Pull request merged**
