### PR TITLE
Code Snippet: Silent option for Internet driver specific capabilities

### PR DESCRIPTION
**Pull request by kjayachandra2000**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Here I have added Java code snippet for `silent` an Internet Driver specific capability [link](https://www.selenium.dev/documentation/en/driver_idiosyncrasies/driver_specific_capabilities/#silent)

### Motivation and Context

This change will help users with a code snippet example.

### Types of changes

- [x] Change to the site (I am attaching a screenshot showing the before and after)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### Before Image
before
### After Image
after

### CODE REVIEW

**Comment by Harsha509** [comment]
HI @kjayachandra2000 ,

Thanks for the PR. 

Can you please sign the CLA to get this merged!

Regards,
Harsha.

**Comment by kjayachandra2000** [comment]
@Harsha509 ,
Thanks for the approval, I have already signed the CLA but not sure why it say's `Contributor License Agreement is not signed yet. `
Please refer to the screenshot
Screen Shot 2020-05-21 at 12 53 13-fullpage

**Comment by diemol** [comment]
@kjayachandra2000 the problem is that the user which made the commits is not associated with your GitHub account. Please double check your email is there https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/adding-an-email-address-to-your-github-account

**Comment by kjayachandra2000** [comment]
I am not able to fix the CLA issue with my login, I will first fix it then will raise a PR

**Pull request closed without merging**
