### PR TITLE
DesiredCapabilities, Local file detector using C#

### PR DESCRIPTION
**Pull request by hiroksarker**
DesiredCapabilities , Local file detector using C#

### CODE REVIEW

**Comment by diemol** [comment]
Hi @hiroksarker, did you have the chance to check my previous [comment](https://github.com/SeleniumHQ/site/pull/53#pullrequestreview-307978926)?

**Comment by hiroksarker** [comment]
@diemol yes, following files translation completed.

**Comment by diemol** [comment]
Not really @hiroksarker, only the English version of the file is changed, what about the other ones?

**Comment by hiroksarker** [comment]
@diemol all translations competed. Would you please check it!

**Comment by jimevans** [comment]
@diemol Please do not merge this docs change until the C# examples no longer refer to `DesiredCapabilities`.

**Comment by diemol** [comment]
I won't @jimevans, thanks for the heads up though. 
I think I will make the changes myself and use:
```
            chromeOptions.BrowserVersion = "67";
            chromeOptions.PlatformName = "Windows XP";
 ```
I'll also remove the DesiredCapabilities text.

**Pull request merged**
