### PR TITLE
Added Setup and Teardown Python Examples to Organizing and Executing Selenium Code

### PR DESCRIPTION
**Pull request by shbenzer**
### **User description**
Added Setup and Teardown Python Examples to Organizing and Executing Selenium Code

### Description
Updated english and japanese versions of Organizing and Executing Selenium Code page to include lines of python code
updated examples/python/getting_started/using_selenium_tests.py to include setup and teardown functions

### Motivation and Context
needed documentation

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

___

### **PR Type**
documentation, enhancement

___

### **Description**
- Added `setup` and `teardown` functions in Python Selenium test examples to improve code organization.
- Updated English and Japanese documentation to include new Python setup and teardown examples.
- Enhanced documentation to provide clearer guidance on organizing and executing Selenium code.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>using_selenium_tests.py</strong><dd><code>Add setup and teardown functions for Selenium tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

examples/python/tests/getting_started/using_selenium_tests.py

<li>Added <code>setup</code> function to initialize WebDriver and open a URL.<br> <li> Added <code>teardown</code> function to quit the WebDriver.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1868/files#diff-aa8c2cd4492a49444ef99b560ecda82475b27fc52ef5804d99b186c4a8c1bddc">+8/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>using_selenium.en.md</strong><dd><code>Update English documentation with Python setup/teardown examples</code></dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/getting_started/using_selenium.en.md

<li>Added Python setup and teardown code examples.<br> <li> Updated documentation to include new code snippets.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1868/files#diff-f521d4cd05fea84ac0fd18184a214f8ac2cd023a7f2c1a7e2b43495504b7b9f0">+9/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>using_selenium.ja.md</strong><dd><code>Update Japanese documentation with Python setup/teardown examples</code></dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/getting_started/using_selenium.ja.md

<li>Added Python setup and teardown code examples.<br> <li> Updated Japanese documentation to include new code snippets.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1868/files#diff-53fac7bfd25fb50de7731415fedc5ea636bcdaa83166f476b3c9e13a691a6c7c">+9/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by diemol — CHANGES_REQUESTED** [review]
Can you also modify the other translated files? Only the English and Japanese were modified.

image

**Comment by diemol** [comment]
It seems these changes are also part of #1871. Can you leave each PR with a single set of changes?

**Comment by shbenzer** [comment]
It seems that all my merges got tangled up together - if you want me to update this I'd have to include the other merges alongside it @diemol

**Comment by diemol** [comment]
Whatever is easier. Maybe for the next PRs, a single set of changes is preferred.

**Comment by shbenzer** [comment]
Sounds good, I'll give it a quick update and push. One moment

**Comment by shbenzer** [comment]
Done

**Review by diemol — APPROVED** [review]

**Pull request merged**
