### PR TITLE
Edit a typo

### PR DESCRIPTION
**Pull request by amirmojiry**
### Description
I removed "the" before a verb (run).

### CODE REVIEW

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @amirmojiry ,

Thanks for the PR.

Can you please make the same changes in other translated pages which are in english.

Thanks!

**Comment by harsha509** [comment]
Hi @amirmojiry,

Did you get a chance to look into above requested changes ?

Thanks!

**Comment by amirmojiry** [comment]
Hi @JS31096,
I've found only one same typo in translation pages and I edited it.
Thank you for your help!

**Review by harsha509 — APPROVED** [review]
Thank you @amirmojiry !

**Comment by harsha509** [comment]
:tada: 🎉  Congratulations on your first contribution for Selenium Docs @amirmojiry. Thank you 🎉 🎉

**Pull request merged**
