### PR TITLE
Add readme files documentation

### PR DESCRIPTION
**Pull request by eaccmk**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description
Added `README.md` files explaining how to set up and run **selenium examples** for :
- javascript
- python
- ruby

### Motivation and Context
When I followed the official Selenium documentation and tried running Selenium examples, I found myself lost.

Therefore, I began with seleniumhq.github.io/examples/... and systematically figured out how to set up and execute each language binding-related test on my own.

- I decided to contribute and enhance the documentation.
- I also made sure that I could successfully set up and run all three sets of examples before pushing changes in this PR.

### Types of changes
- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist
- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by titusfortner** [comment]
This is great. Why did you delete the Python one? That should be the correct instructions.

**Comment by eaccmk** [comment]
> This is great. Why did you delete the Python one? That should be the correct instructions.

It's back !

**Comment by eaccmk** [comment]
ready to be merged once reviewed.

**Review by titusfortner — APPROVED** [review]

**Review by diemol — APPROVED** [review]
Thank you, @eaccmk!

**Pull request merged**
