### PR TITLE
Migrate and update ruby code examples with internet explorer

### PR DESCRIPTION
**Pull request by aguspe**
### Description
This PR migrates and adds code examples using ruby for IE

### Motivation and Context
It's important to keep the examples and documentation up to date to facilitate usage by all the users

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist
- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

___

### **PR Type**
Enhancement, Documentation

___

### **Description**
- Added comprehensive test cases for various Internet Explorer options in Ruby.
- Updated documentation to link to the new Ruby test cases for Internet Explorer options.
- Ensured consistency and accuracy in Ruby code examples across multiple languages (English, Japanese, Portuguese, Chinese).

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>internet_explorer_spec.rb</strong><dd><code>Add comprehensive test cases for Internet Explorer options in Ruby.</code></dd></summary>
<hr>
      
examples/ruby/spec/browsers/internet_explorer_spec.rb

<li>Added multiple test cases for Internet Explorer options.<br> <li> Included tests for file upload dialog timeout, clean session, zoom <br>settings, and protected mode settings.<br> <li> Added tests for silent option and command line options.<br> <li> Ensured proper driver quit in each test case.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1748/files#diff-0ae188a376b0174e0ca12b28866fe852ecec6711f257216da452ed61630ef3bf">+57/-1</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>internet_explorer.en.md</strong><dd><code>Update Ruby code examples in Internet Explorer documentation.</code></dd></summary>
<hr>
      
website_and_docs/content/documentation/webdriver/browsers/internet_explorer.en.md

<li>Updated Ruby code examples with links to the new test cases.<br> <li> Ensured consistency in documentation for Ruby examples.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1748/files#diff-b887e55fa380db36be93803cc07213e0bfc1b22d72bd64e9716799c59f9970ec">+23/-52</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>internet_explorer.ja.md</strong><dd><code>Update Ruby code examples in Japanese Internet Explorer documentation.</code></dd></summary>
<hr>
      
website_and_docs/content/documentation/webdriver/browsers/internet_explorer.ja.md

<li>Updated Ruby code examples with links to the new test cases.<br> <li> Ensured consistency in documentation for Ruby examples.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1748/files#diff-d2dae06f1fde6e06d1b014e3d830b15bb2e7b6c7eea3472e304acbed2d770a02">+24/-53</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>internet_explorer.pt-br.md</strong><dd><code>Update Ruby code examples in Portuguese Internet Explorer </code><br><code>documentation.</code></dd></summary>
<hr>
      
website_and_docs/content/documentation/webdriver/browsers/internet_explorer.pt-br.md

<li>Updated Ruby code examples with links to the new test cases.<br> <li> Ensured consistency in documentation for Ruby examples.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1748/files#diff-fe2d01308c167a177a9d3bbb5ab5d10e71e644ca3fe386c5936fd9de12346b03">+24/-55</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>internet_explorer.zh-cn.md</strong><dd><code>Update Ruby code examples in Chinese Internet Explorer documentation.</code></dd></summary>
<hr>
      
website_and_docs/content/documentation/webdriver/browsers/internet_explorer.zh-cn.md

<li>Updated Ruby code examples with links to the new test cases.<br> <li> Ensured consistency in documentation for Ruby examples.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1748/files#diff-492f3c9f55f8b46ec55057baee400031d06cc5744d6d630ea1f160d849e65d86">+24/-53</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by harsha509 — APPROVED** [review]
Thank you @aguspe !

**Comment by aguspe** [comment]
@harsha509 I saw some window tests failing should I skip the IE examples I added? It's a bit difficult for me locally to test IE due to my computer being a mac

**Comment by harsha509** [comment]
> @harsha509 I saw some window tests failing should I skip the IE examples I added? It's a bit difficult for me locally to test IE due to my computer being a mac

we need to execute tests in chromium edge (IE in edge mode), can you try setting this option `attach_to_edge_chrome: true`

**Comment by aguspe** [comment]
> > @harsha509 I saw some window tests failing should I skip the IE examples I added? It's a bit difficult for me locally to test IE due to my computer being a mac
> 
> we need to execute tests in chromium edge (IE in edge mode), can you try setting this option `attach_to_edge_chrome: true`

Perfect, I will do it tomorrow and update the whole PR

**Comment by aguspe** [comment]
@harsha509 the whole PR is updated, I hope that does the trick :)

**Comment by aguspe** [comment]
I can see that the following 2 tests are failing on windows:

  1) Internet Explorer Options adds the silent option
     Failure/Error: Selenium::WebDriver.for(:ie, options: @options)

     Selenium::WebDriver::Error::WebDriverError:
       These options are not w3c compliant: {"silent"=>{:silent=>true}}
     ./spec/browsers/internet_explorer_spec.rb:54:in `block (3 levels) in <top (required)>'

  2) Internet Explorer Options launches ie with the create process api
     Failure/Error: Selenium::WebDriver.for(:ie, options: @options)

     Selenium::WebDriver::Error::SessionNotCreatedError:
       Unexpected error launching Internet Explorer. Unable to use CreateProcess() API. To use CreateProcess() with Internet Explorer 8 or higher, the value of registry setting in HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main\TabProcGrowth must be '0'.
     ./spec/browsers/internet_explorer_spec.rb:65:in `block (3 levels) in <top (required)>'
     
     I will try to set up parallels and see if I can reproduce them on my mac

**Comment by aguspe** [comment]
Hi @harsha509 I hope you are doing well, I updated the 2 tests that were failing and hopefully the pipeline will be green this time

**Comment by aguspe** [comment]
Hi @harsha509 I re-merged the trunk, so I hope the tests are ready to run again, after this I will continue updating the ruby docs, thank you so much!

**Comment by aguspe** [comment]
Hi @harsha509 I looked more into it and I found that the ruby library does not support the silent option so I added it on this PR as it is on other bindings such as java and js, once the PR is merged, the test will stop failing:

https://github.com/SeleniumHQ/selenium/pull/14152

**Comment by aguspe** [comment]
The PR adding support for the silent capability has been merged https://github.com/SeleniumHQ/selenium/pull/14152, so for now I will skip the silent test until the release of selenium 4.22.0, so everything should work now @harsha509

**Pull request merged**
