### PR TITLE
Added Python Example to PrintPage Documentation

### PR DESCRIPTION
**Pull request by shbenzer**
### **User description**
Added python example to Printing in Print Options section

### Description
added test_print_page.py
added code example to all translations of print_option.md

### Motivation and Context
code example
hacktober

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

___

### **PR Type**
Documentation, Tests

___

### **Description**
- Added a new Python test file to demonstrate the `print_page()` functionality using Selenium.
- Updated the documentation in multiple languages (English, Japanese, Portuguese, Chinese) to include the new Python code example.
- Linked the documentation to the newly added Python test example for better clarity and usability.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>test_prints_page.py</strong><dd><code>Add Python test for print page functionality</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

examples/python/tests/interactions/test_prints_page.py

<li>Added a new test file for printing a page using Selenium.<br> <li> Implemented a fixture for setting up and tearing down the WebDriver.<br> <li> Created a test function to verify the print page functionality.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/2009/files#diff-e71cb7856ad4e63fe00b38dbe636f18d42ed892a6e7e1271508590190baa8e49">+15/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>print_page.en.md</strong><dd><code>Update English documentation with Python print page example</code></dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/interactions/print_page.en.md

<li>Added Python code example for <code>print_page()</code> function.<br> <li> Linked to the new Python test example in the documentation.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/2009/files#diff-ab83295d85363fa0e82b30ca84fb9727d0e73fecc3de7b707767c39343a2459c">+3/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>print_page.ja.md</strong><dd><code>Update Japanese documentation with Python print page example</code></dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/interactions/print_page.ja.md

<li>Added Python code example for <code>print_page()</code> function.<br> <li> Linked to the new Python test example in the documentation.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/2009/files#diff-b2a566eb1a7cdfae34aa2dd15f597e4b8fd40fbdaadc1a3db3ce0fe850e7dc92">+3/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>print_page.pt-br.md</strong><dd><code>Update Portuguese documentation with Python print page example</code></dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/interactions/print_page.pt-br.md

<li>Added Python code example for <code>print_page()</code> function.<br> <li> Linked to the new Python test example in the documentation.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/2009/files#diff-d4342199d4feb4c990d7fa275bf4912397b428908760f58d26e1326ba4aea21a">+3/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>print_page.zh-cn.md</strong><dd><code>Update Chinese documentation with Python print page example</code></dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/interactions/print_page.zh-cn.md

<li>Added Python code example for <code>print_page()</code> function.<br> <li> Linked to the new Python test example in the documentation.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/2009/files#diff-33cd5d0d8234827d7cacbb49b609e33192310123a67cbe0910f68a66a2b5eb6d">+3/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by shbenzer** [comment]
Part of issue #1941

**Review by harsha509 — APPROVED** [review]
Thank you @shbenzer !

**Comment by shbenzer** [comment]
Looks like that failure is from move_mouse_by_offset, not my code luckily lol

**Review by A1exKH — APPROVED** [review]
Code LGTM.
There is 1 failed check for this PR, but I don't see any affected code in this PR.

**Pull request merged**
