### PR TITLE
Double espace remplacé par un espace simple

### PR DESCRIPTION
**Pull request by Crank4**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [x] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by Crank4** [comment]
Double space replace by a single space

**Review by harsha509 — APPROVED** [review]
Thank you @TritzA !

**Comment by harsha509** [comment]
HI @TritzA ,

Could you please sign the CLA to get this merged!

Thanks,
Harsha

**Comment by Crank4** [comment]
Hi Sri Harsha,

I signed the CLA. Can you now merge my commits ?

Thanks,
Antonin

Le dim. 25 avr. 2021 à 05:11, Sri Harsha ***@***.***> a
écrit :

**Review by diemol — APPROVED** [review]

**Pull request merged**
