### PR TITLE
Create Directory for running Java Examples

### PR DESCRIPTION
**Pull request by titusfortner**
@diemol per our discussion on Slack, what do you think of something like this where we put examples in the `example` directory? We can execute these in a github action if we want as well.

### CODE REVIEW

**Review by diemol — COMMENTED** [review]
I think it only makes sense to create this directory and merge this when we are actually using the code in the examples. Not before, as we could leave this half done.

**Comment by titusfortner** [comment]
Yeah, this is the start of what I was going to do for #825 
I mostly just want to know where we should be putting the example code, and if this makes the most sense.

**Comment by titusfortner** [comment]
Moving to draft while reworking this

**Comment by titusfortner** [comment]
Closing in favor of something more comprehensive

**Pull request closed without merging**
