### PR TITLE
Updated Python Examples for Options

### PR DESCRIPTION
**Pull request by shbenzer**
### **User description**
Updated Python examples in Browser Options

### Description
added examples to test_options.py
made examples more consistent with other language examples
updated all translations of index.mds

### Motivation and Context
Issue #1983 

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

___

### **PR Type**
Tests, Documentation

___

### **Description**
- Added new Python test cases for browser options including browser name, version, and platform name.
- Updated existing Python test cases to improve consistency and ensure all tests navigate to and quit from the Selenium website.
- Updated documentation in multiple languages (English, Japanese, Portuguese, Chinese) to reflect new line numbers for Python code examples.
- Ensured consistency across different language examples in the documentation.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>test_options.py</strong><dd><code>Enhance and unify Python test examples for browser options</code></dd></summary>
<hr>

examples/python/tests/drivers/test_options.py

<li>Added new test cases for browser name, version, and platform name.<br> <li> Updated existing test cases to improve consistency.<br> <li> Changed <code>FirefoxOptions</code> to <code>ChromeOptions</code> in <code>test_set_window_rect</code>.<br> <li> Ensured all tests navigate to and quit from the Selenium website.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/2010/files#diff-2634464e892392fa3ffdf1940368c555053d49f5d1491886253b739676ea7730">+31/-25</a>&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>options.en.md</strong><dd><code>Update English documentation with new Python example references</code></dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/drivers/options.en.md

<li>Updated Python code example references to new line numbers.<br> <li> Ensured consistency with updated Python test examples.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/2010/files#diff-62bab9f28d27a7f462881a28eca384a0e534a730f849248f396d171820bc748e">+14/-14</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>options.ja.md</strong><dd><code>Update Japanese documentation with new Python example references</code></dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/drivers/options.ja.md

<li>Updated Python code example references to new line numbers.<br> <li> Ensured consistency with updated Python test examples.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/2010/files#diff-2ed475220bde1368cfa3883d71db179409ddaf9ccbaea847ed3f6ffe816321e4">+14/-14</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>options.pt-br.md</strong><dd><code>Update Portuguese documentation with new Python example references</code></dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/drivers/options.pt-br.md

<li>Updated Python code example references to new line numbers.<br> <li> Ensured consistency with updated Python test examples.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/2010/files#diff-6eaa598a13e9d64c6afbd54b84aef470520557f08c4d183ffb28ceb9ed04d0bb">+14/-14</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>options.zh-cn.md</strong><dd><code>Update Chinese documentation with new Python example references</code></dd></summary>
<hr>

website_and_docs/content/documentation/webdriver/drivers/options.zh-cn.md

<li>Updated Python code example references to new line numbers.<br> <li> Ensured consistency with updated Python test examples.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/seleniumhq.github.io/pull/2010/files#diff-9b23b749355db8154bfcc4a1d70f809b7d4e91a7b3044f9ac74a6c1a005873d6">+14/-14</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by harsha509 — APPROVED** [review]
Thank you @shbenzer !

**Review by A1exKH — APPROVED** [review]
LGTM.

**Comment by shbenzer** [comment]
Failure has nothing to do with submitted code - though I do see it occasionally on other PRs. Do we know why this test fails on Ubuntu? `tests/actions_api/test_mouse.py::test_move_by_offset_from_viewport_origin_ab` @harsha509 @A1exKH

**Comment by harsha509** [comment]
> tests/actions_api/test_mouse.py::test_move_by_offset_from_viewport_origin_ab

Looks like a flaky one..!

Looking into it!

**Pull request merged**
