### PR TITLE
Bug fix 1033 link to download driver

### LINKED ISSUE #1033: [🐛 Bug]: Page loops in documentation
### What happened?

On the [Install browser drivers page](https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/) text there is a reference for the [driver configuration page](https://www.selenium.dev/documentation/webdriver/drivers/), which has only a single line and a reference back to the  [Install browser drivers page](https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/). Looks like a documentation bug to the user.

### What browsers and operating systems are you seeing the problem on?

Chrome, Edge

### PR DESCRIPTION
**Pull request by eaccmk**
### Description
This PR fixes #1033 for all languages.

There was a typo in page reference link, now fixed.

### Motivation and Context
Fix bug #1033 

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Bug fix
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Review by titusfortner — APPROVED** [review]

**Comment by eaccmk** [comment]
I have synced and updated the branch with trunk, can I please get a hand to merge this PR ? maybe @titusfortner

**Review by harsha509 — APPROVED** [review]
Thank you @eaccmk !

**Comment by harsha509** [comment]
Congratulations on your first contribution to Selenium Docs @eaccmk 🎉 🎉 🎉

**Comment by titusfortner** [comment]
Thanks for the contribution. I can review/approve it by phone easily enough, but when I try to merge it, it's complicated, so I can only do it when I get back to a computer. Thanks for the assist @harsha509 .

**Pull request merged**
