### PR TITLE
Modify: Revamping kotlin code samples (tested with selenium-alpha-3-jar)

### PR DESCRIPTION
**Pull request by Harsha509**
**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [x] Code example added (and I also added the example to all translated languages)
- [x] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

### CODE REVIEW

**Comment by Harsha509** [comment]
Hi @diemol ,

Current kotlin samples codes are not working as expected . I would like to test the remaining code samples and i would like provide the PR.

Please suggest on this.

Regards,
Sri Harsha

**Comment by manoj9788** [comment]
You can always have a draft PR and keep working on it!

**Comment by Harsha509** [comment]
Hi @manoj9788 ,

Sure. I will maintain a draft PR for this.

Thanks,
Harsha

**Comment by Harsha509** [comment]
Hi @manoj9788 ,

I am unable make this 'ready' PR to 'draft' PR Currently. Please let me know if this can be merged (or) shall i cancel the PR. 

Thanks,
Harsha

**Comment by manoj9788** [comment]
Please give us some time to review and then we shall help to get this merged if everything looks good.

**Comment by Harsha509** [comment]
Sure @diemol. will provide small PRs. Thanks for the review.

**Pull request merged**
